### ISSUE TITLE
metal-auto-capture feature panics in framework.rs

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu-rs#111]
So
1. as of today, I don't think the cfg can ever fire, because there is no exposed top level feature "metal-auto-capture"
```rust
    log::info!("Entering render loop...");
    event_loop.run(move |event, _, control_flow| {
        *control_flow = if cfg!(feature = "metal-auto-capture") {
            ControlFlow::Exit
        } else {
            ControlFlow::Poll
        };
```
2. regardless, if we manually set the control flow to exit, and compile with `wgn/metal-auto-capture`, it appears to cause a panic somewhere in winit:

```
RUST_BACKTRACE=full cargo run --example skybox
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/examples/skybox`
Copying skybox image 0 of size 512,512 to gpu
Copying skybox image 1 of size 512,512 to gpu
Copying skybox image 2 of size 512,512 to gpu
Copying skybox image 3 of size 512,512 to gpu
Copying skybox image 4 of size 512,512 to gpu
Copying skybox image 5 of size 512,512 to gpu
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0:        0x10f92c772 - backtrace::backtrace::libunwind::trace::h5408e5110cf529da
                               at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:        0x10f92c772 - backtrace::backtrace::trace_unsynchronized::he52f6c5ff46c369c
                               at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:        0x10f92c772 - std::sys_common::backtrace::_print::hb80f2114c7310691
                               at src/libstd/sys_common/backtrace.rs:47
   3:        0x10f92c772 - std::sys_common::backtrace::print::h57cd02882f2ac93b
                               at src/libstd/sys_common/backtrace.rs:36
   4:        0x10f92c772 - std::panicking::default_hook::{{closure}}::h6e0c5011619dccf8
                               at src/libstd/panicking.rs:200
   5:        0x10f92c43b - std::panicking::default_hook::h673b9cd39a829714
                               at src/libstd/panicking.rs:214
   6:        0x10f92cf60 - std::panicking::rust_panic_with_hook::h7d6a669f1a899680
                               at src/libstd/panicking.rs:477
   7:        0x10f92ca8d - std::panicking::continue_panic_fmt::h682bc3f8dac9c5a1
                               at src/libstd/panicking.rs:384
   8:        0x10f92c979 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:        0x10f94b562 - core::panicking::panic_fmt::he11aece98ed722cd
                               at src/libcore/panicking.rs:85
  10:        0x10f94b4a7 - core::panicking::panic::h89241d71a860ed98
                               at src/libcore/panicking.rs:49
  11:        0x10f8f7516 - core::option::Option<T>::unwrap::h4e29946ffb482f65
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:12
  12:        0x10f8ca82f - winit::platform_impl::platform::app_state::AppState::wakeup::h6416ae5371efc2be
                               at /Users/ataraxis/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/macos/app_state.rs:209
  13:        0x10f8d13a0 - winit::platform_impl::platform::observer::control_flow_begin_handler::hc4003e93ba88a58c
                               at /Users/ataraxis/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/macos/observer.rs:116
  14:     0x7fff2fe57e88 - <unknown>
  15:     0x7fff2fe57dbd - <unknown>
  16:     0x7fff2fdfa7c5 - <unknown>
  17:     0x7fff2fdf9e0e - <unknown>
  18:     0x7fff2f0e69db - <unknown>
  19:     0x7fff2f0e6715 - <unknown>
  20:     0x7fff2f0e64a6 - <unknown>
  21:     0x7fff2d480ffb - <unknown>
  22:     0x7fff2d47fd93 - <unknown>
  23:     0x7fff2d479eb0 - <unknown>
  24:        0x10f90976a - <() as objc::message::MessageArguments>::invoke::h2e2f5e9265ba1215
                               at /Users/ataraxis/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
  25:        0x10f90650e - objc::message::platform::send_unverified::h16469769d79d83d4
                               at /Users/ataraxis/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
  26:        0x10edbd7ff - objc::message::send_message::h2271094f3ce52ef4
                               at /Users/ataraxis/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
  27:        0x10edbd7ff - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::hab7bceb5cbffd788
                               at /Users/ataraxis/projects/wgpu-rs/wgpu-rs/<::objc::macros::msg_send macros>:14
  28:        0x10edbda68 - winit::platform_impl::platform::event_loop::EventLoop<T>::run::h083a4b1264b6cf6c
                               at /Users/ataraxis/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/macos/event_loop.rs:89
  29:        0x10edb0c9d - winit::event_loop::EventLoop<T>::run::h11cccc24a50bbcb7
                               at /Users/ataraxis/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/event_loop.rs:148
  30:        0x10edb3f5d - skybox::framework::run::hef659713b6dfb3b6
                               at examples/skybox/../framework.rs:114
  31:        0x10edbafd8 - skybox::main::hccc2bd8c540c1121
                               at examples/skybox/main.rs:297
  32:        0x10edaf882 - std::rt::lang_start::{{closure}}::h818d91b4628d53a6
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  33:        0x10f92c8f8 - std::rt::lang_start_internal::{{closure}}::ha9fcfb3b278bcf3f
                               at src/libstd/rt.rs:49
  34:        0x10f92c8f8 - std::panicking::try::do_call::ha6f6dadf842d3c9c
                               at src/libstd/panicking.rs:296
  35:        0x10f933e9f - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  36:        0x10f92d3de - std::panicking::try::h3bc5f919887df4c4
                               at src/libstd/panicking.rs:275
  37:        0x10f92d3de - std::panic::catch_unwind::hd36fe659e375f196
                               at src/libstd/panic.rs:394
  38:        0x10f92d3de - std::rt::lang_start_internal::hc1ac2c20e9f8edf2
                               at src/libstd/rt.rs:48
  39:        0x10edaf862 - std::rt::lang_start::hcf34b62a054a6080
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  40:        0x10edbb002 - skybox::main::hccc2bd8c540c1121
```

**Comment by cwfitzgerald** [comment]
Closing as out of date as that feature no longer exists anywhere as far as I can tell.
