### ISSUE TITLE
SwapChain::get_next_texture panic on mac

### ISSUE THREAD

**Issue by bch29** [gfx-rs/wgpu-rs#121]
This seems to happen occasionally when I leave my program running for a few minutes while switching to other windows. I haven't found a way to consistently reproduce it. Stack trace below (with some paths and parts of the stack from my project censored).

If it is the case that `SwapChain::get_next_texture` is unavoidably fallible sometimes, perhaps you could add a `try_get_next_texture` method that returns an `Option` or `Result`?

```
thread 'main' panicked at 'assertion failed: !drawable.as_ptr().is_null()', <censored_path>/src/window.rs:481:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:411
   8: <gfx_backend_metal::window::Surface as gfx_hal::window::PresentationSurface<gfx_backend_metal::Backend>>::acquire_image::{{closure}}
             at <censored_path>/src/window.rs:481
   9: objc::rc::autorelease::autoreleasepool
             at <censored_path>/src/rc/autorelease.rs:29
  10: <gfx_backend_metal::window::Surface as gfx_hal::window::PresentationSurface<gfx_backend_metal::Backend>>::acquire_image
             at <censored_path>/src/window.rs:479
  11: wgpu_native::swap_chain::swap_chain_get_next_texture
             at <censored_path>/src/swap_chain.rs:156
  12: wgpu_swap_chain_get_next_texture
             at <censored_path>/src/swap_chain.rs:214
  13: wgpu::SwapChain::get_next_texture
             at <censored_path>/src/lib.rs:1355
  ...
  16: <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:794
  17: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at <censored_path>/src/platform_impl/macos/app_state.rs:58
  18: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at <censored_path>/src/platform_impl/macos/app_state.rs:157
  19: winit::platform_impl::platform::app_state::AppState::cleared
             at <censored_path>/src/platform_impl/macos/app_state.rs:274
  20: winit::platform_impl::platform::observer::control_flow_end_handler
             at <censored_path>/src/platform_impl/macos/observer.rs:135
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <() as objc::message::MessageArguments>::invoke
             at <censored_path>/src/message/mod.rs:128
  32: objc::message::platform::send_unverified
             at <censored_path>/src/message/apple/mod.rs:27
  33: objc::message::send_message
             at <censored_path>/src/message/mod.rs:178
  34: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at ./<::objc::macros::msg_send macros>:15
  35: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at <censored_path>/src/platform_impl/macos/event_loop.rs:89
  36: winit::event_loop::EventLoop<T>::run
             at <censored_path>/src/event_loop.rs:148
  ...
  41: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  42: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  43: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  44: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  45: std::panicking::try
             at src/libstd/panicking.rs:275
  46: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  47: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  48: std::rt::lang_start
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  ...
```

**Comment by kvark** [comment]
Interesting, we need to figure out what happens there.

fwiw, `get_next_texture` already returns a `Result`: https://github.com/gfx-rs/wgpu-rs/blob/cbdd74fb408d87c04423bd375806b3b6c1be1bb0/src/lib.rs#L1356

**Comment by bch29** [comment]
After a bit more experimentation this usually seems to happen when in 'Mission Control' (Ctrl+Up) to switch between windows -- usually a short time after entering Mission Control, but not immediately. In case you need more information: my program is running in a normal (not fullscreen) window, and I'm on MacOS Sierra on an early 2015 13" MacBook Pro.

Good to see that `get_next_texture` will return a `Result` in the next release!

**Comment by seivan** [comment]
@bch29 Are you running with Winit or SDL2? 
Did it happen exclusively with Mission Control, or could it be that the Window lost focus triggered it? 

Wondering if it's related to https://github.com/gfx-rs/wgpu/issues/78

**Comment by bch29** [comment]
I'm using winit, as the traceback shows. It is possible a lost focus event triggers this but I have only observed it through mission control. I do not think this is the same issue, however, because I didn't notice any lagging or memory spikes and the panic message is different.

**Comment by cwfitzgerald** [comment]
Can you reproduce this on the latest wgpu-rs master?
