### ISSUE TITLE
cube example fails on Lubuntu 16.04.6 LTS

### ISSUE THREAD

**Issue by nghenglim** [gfx-rs/wgpu-rs#132]
able to run hello-compute, however cube example failed

~~~
liamng@liamng-OMEN-by-HP-Laptop:/e/development/ossc/wgpu-rs(master)$ RUST_BACKTRACE=full cargo run --example cube
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/examples/cube`
thread 'main' panicked at 'assertion failed: suf.supports_queue_family(&adapter.raw.queue_families[0])', /home/liamng/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/73b33ea/wgpu-core/src/device.rs:1924:13
stack backtrace:
   0:     0x565484bc2ef4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x565484bc2ef4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x565484bc2ef4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x565484bc2ef4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x565484be9aac - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x565484bbf617 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x565484bc5a65 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x565484bc5a65 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x565484bc5a65 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x565484bc5756 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x565484bc6165 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x56548474b1a3 - std::panicking::begin_panic::h2e945b7c37a90f1b
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:407
  12:     0x56548461aa24 - wgpu_core::device::<impl wgpu_core::hub::Global<F>>::device_create_swap_chain::ha8b826dfd0af576f
                               at /home/liamng/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/73b33ea/wgpu-native/<::std::macros::panic macros>:3
  13:     0x5654845d5013 - wgpu_device_create_swap_chain
                               at /home/liamng/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/73b33ea/wgpu-native/src/device.rs:306
  14:     0x5654843ef47e - wgpu::Device::create_swap_chain::h30bb2fa7bf889002
                               at src/lib.rs:857
  15:     0x565484159e98 - cube::framework::run::h0eab5a2720a965df
                               at examples/cube/../framework.rs:119
  16:     0x565484195bf5 - cube::main::ha4ec82abebd2516f
                               at examples/cube/main.rs:364
  17:     0x565484159770 - std::rt::lang_start::{{closure}}::he3441730556d2411
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  18:     0x565484bc5b93 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  19:     0x565484bc5b93 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  20:     0x565484bce33a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  21:     0x565484bc665d - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  22:     0x565484bc665d - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  23:     0x565484bc665d - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  24:     0x565484159749 - std::rt::lang_start::hc58c8f32a6e81d01
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  25:     0x565484195c2a - main
  26:     0x7fb0cb03d830 - __libc_start_main
  27:     0x565484139c99 - _start
  28:                0x0 - <unknown>
~~~ 

and I have `GP107M [GeForce GTX 1050 Mobile]`

and rustc version `rustc 1.39.0 (4560ea788 2019-11-04)`

**Comment by kvark** [comment]
Interesting, thanks for the bug report!
Does `vkcube` work? Could you also check gfx-rs or ash examples?

**Comment by nghenglim** [comment]
so it default to vulkan for linux? My vulkan installation somehow not completed so vkcube does not work
~~~
liamng@liamng-OMEN-by-HP-Laptop:/e/development/ossc/gfx/examples(master)$ vkcube
Could not find both graphics and present queues
~~~

however I am able to run quad example in gfx using `gl`
~~~
liamng@liamng-OMEN-by-HP-Laptop:/e/development/ossc/gfx/examples(master)$ cargo run --bin quad --features=gl
~~~

**Comment by kvark** [comment]
Vulkan is the one and only option for wgpu-rs on Linux today. In the future, we'll have GL support (again).
