### ISSUE TITLE
Window closes when resized (Linux)

### ISSUE THREAD

**Issue by ghost** [gfx-rs/wgpu-rs#136]
![2019-11-3011-08-19](https://user-images.githubusercontent.com/49613045/69899133-590d7b80-1362-11ea-9461-2d477a897899.gif)

OS: Fedora 31
Display Manager: Xorg

Log:
```
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 32767', /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2717:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  15: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2717
  16: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2568
  17: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/vec.rs:1796
  18: <gfx_backend_vulkan::window::Surface as gfx_hal::window::PresentationSurface<gfx_backend_vulkan::Backend>>::acquire_image
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.4.0/src/window.rs:507
  19: wgpu_core::swap_chain::<impl wgpu_core::hub::Global<F>>::swap_chain_get_next_texture
             at /home/master/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/b51053d/wgpu-core/src/swap_chain.rs:149
  20: wgpu_swap_chain_get_next_texture
             at /home/master/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/b51053d/wgpu-native/src/device.rs:366
  21: wgpu::SwapChain::get_next_texture
             at src/lib.rs:1410
  22: cube::framework::run::{{closure}}
             at examples/cube/../framework.rs:167
  23: winit::platform_impl::platform::sticky_exit_callback
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:693
  24: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:305
  25: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:389
  26: winit::platform_impl::platform::EventLoop<T>::run
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:640
  27: winit::event_loop::EventLoop<T>::run
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/event_loop.rs:148
  28: cube::framework::run
             at examples/cube/../framework.rs:128
  29: cube::main
             at examples/cube/main.rs:364
  30: std::rt::lang_start::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  31: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  32: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  34: std::panicking::try
             at src/libstd/panicking.rs:271
  35: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  36: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  37: std::rt::lang_start
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  38: main
  39: __libc_start_main
  40: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by glalonde** [comment]
I'm also getting this on my integrated gpu(intel). Would this be from wgpu or one of the lower levels?

```
TRACE 1.782s [wgpu_native::command::allocator:143] recycling comb submitted in 99 when 99 is done
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 32767', /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2796:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:96
  15: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2796
  16: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2647
  17: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/vec.rs:1861
  18: <gfx_backend_vulkan::window::Surface as gfx_hal::window::PresentationSurface<gfx_backend_vulkan::Backend>>::acquire_image
             at /home/glalonde/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.4.0/src/window.rs:507
  19: wgpu_native::swap_chain::swap_chain_get_next_texture
             at /home/glalonde/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.1/src/swap_chain.rs:156
  20: wgpu_swap_chain_get_next_texture
             at /home/glalonde/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.1/src/swap_chain.rs:214
  21: wgpu::SwapChain::get_next_texture
             at /home/glalonde/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1355
  22: hello_triangle::framework::run::{{closure}}
             at examples/hello_triangle/../framework.rs:131
  23: winit::platform_impl::platform::sticky_exit_callback
             at /home/glalonde/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:693
  24: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/glalonde/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:305
  25: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/glalonde/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:389
  26: winit::platform_impl::platform::EventLoop<T>::run
             at /home/glalonde/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:640
  27: winit::event_loop::EventLoop<T>::run
             at /home/glalonde/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/event_loop.rs:148
  28: hello_triangle::framework::run
             at examples/hello_triangle/../framework.rs:92
  29: hello_triangle::main
             at examples/hello_triangle/main.rs:207
  30: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  31: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  32: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  34: std::panicking::try
             at src/libstd/panicking.rs:265
  35: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  36: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  37: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  38: main
  39: __libc_start_main
  40: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
TRACE 1.933s [wgpu_native::device:239] Active submission 100 is done
TRACE 1.933s [wgpu_native::command::allocator:143] recycling comb submitted in 100 when 100 is done
```

**Comment by kvark** [comment]
Weird, we do check for errors in `acquire_xxx`, so something is off down the stack.

**Comment by glalonde** [comment]
Looks like the large index is coming out of this line right here:
https://github.com/MaikKlein/ash/commit/bd69ab969cc36d6bd5fef37fa3155968e218d4ae#diff-6002a25b0a437ac68a4d44e1e219121dL53

This has been changed from uninitialized to zeroed, so we probably wouldn't see this exact issue after upgrading Ash. But the problem probably still exists because the vulkan function looks like it's saying VK_SUCCESS but it is actually not doing what it is supposed to because it isn't changing the index. fwiw, changing the line from uninitialized to zeroed, does fix my specific issue in that it doesn't crash anymore. I wonder if this is an intel driver issue?

```
[glalonde@trochanter ~]$ pacman -Q --info vulkan-intel
Name            : vulkan-intel
Version         : 19.2.6-1
Description     : Intel's Vulkan mesa driver
Architecture    : x86_64
URL             : https://www.mesa3d.org/
Licenses        : custom
Groups          : None
Provides        : vulkan-driver
Depends On      : wayland  libx11  libxshmfence  libdrm
Optional Deps   : vulkan-mesa-layer: a vulkan layer to display information using an overlay
Required By     : None
Optional For    : vulkan-icd-loader
Conflicts With  : None
Replaces        : None
Installed Size  : 5.67 MiB
Packager        : Laurent Carlier <lordheavym@gmail.com>
Build Date      : Sat 23 Nov 2019 07:34:47 PM PST
Install Date    : Wed 27 Nov 2019 08:19:53 PM PST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by glalonde** [comment]
Also seems to not be a problem after building and installing mesa 20.0 from source: https://aur.archlinux.org/packages/mesa-git/

Not sure if the important variable there is building from source or not, but using the Arch official package for 19.3.1 still has the problem: https://www.archlinux.org/packages/extra/x86_64/vulkan-intel/

**Comment by cwfitzgerald** [comment]
Can you still reproduce this on latest wgpu-rs master?
