### ISSUE TITLE
Timeout when acquiring next swap chain texture

### ISSUE THREAD

**Issue by wezm** [gfx-rs/wgpu-rs#164]
All the examples panic on my system after showing the initial frame. The message is:

> Timeout when acquiring next swap chain texture

It originates on lines like:

```rust
            event::Event::RedrawRequested(_) => {
                let frame = swap_chain
                    .get_next_texture()
                    .expect("Timeout when acquiring next swap chain texture");
```

The `describe` example runs and reports this info:

```
AdapterInfo { name: "Radeon RX 560 Series", vendor: 4098, device: 26623, device_type: DiscreteGpu }
```

I'm running Arch Linux on a desktop AMD Ryzen machine. The above graphics card is the only one present (no integrated graphics), amdgpu driver (open source). Linux kernel 5.4.13-arch1-1. Let me know if there's any other debugging/info I can do/provide.

**Comment by kvark** [comment]
Thanks for the report! Could you try running `vkcube` from "vulkan-tools" package, or any `ash` examples?

**Comment by wezm** [comment]
`vkcube` appears to run fine (spinning cube with good framerate).

[ash](https://github.com/MaikKlein/ash) `triangle` and `texture` examples panic as follows:

```
thread 'main' panicked at 'Instance creation error: VkError(ERROR_LAYER_NOT_PRESENT)', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::expect
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
  16: examples::ExampleBase::new
             at examples/src/lib.rs:347
  17: texture::main
             at examples/src/bin/texture.rs:28
  18: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  22: std::panicking::try
             at src/libstd/panicking.rs:265
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  25: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  26: main
  27: __libc_start_main
  28: _start
```

I'm using `amdvlk` as my vulkan driver. I'm not sure if the other two AMD Vulkan drivers listed [here](https://wiki.archlinux.org/index.php/Vulkan#Installation) are worth trying.

Output from `vulkaninfo` is attached:

[vulkaninfo.txt](https://github.com/gfx-rs/wgpu-rs/files/4093924/vulkaninfo.txt)

**Comment by kvark** [comment]
@wezm thank you! Looks like we need to resolve this at the Ash level first.
@MaikKlein would you be able to take a look?

**Comment by MaikKlein** [comment]
@wezm The ash samples panic because you don't have any layers installed. I assume this is unrelated to the gfx panic.

**Comment by kvark** [comment]
@MaikKlein that's because Ash requires debug layers when built in debug? I mean, Vulkan should generally work without layers.

**Comment by MaikKlein** [comment]
> that's because Ash requires debug layers when built in debug?

No just the examples require it at the moment.

**Comment by kvark** [comment]
@MaikKlein got it, thanks!
@wezm Alright, I think what we need here is the validation layer output when running wgpu-rs. Please install the Vulkan SDK and debug layers and run again. On linux, the debug output is printed automatically to the console.

**Comment by wezm** [comment]
Ok I installed the `vulkan-devel` group:

```
:: There are 7 members in group vulkan-devel:
:: Repository extra
   1) spirv-tools  2) vulkan-extra-layers  3) vulkan-headers  4) vulkan-html-docs  5) vulkan-tools  6) vulkan-trace
   7) vulkan-validation-layers
```

Rerunning `texture` and `triangle` examples from `ash` now work. I can't seem to see any debug output in the terminal or systemd journal though.

**Comment by kvark** [comment]
No console output for wgpu-rs examples?

**Comment by wezm** [comment]
Ahh yep:

```
$ RUST_BACKTRACE=1 cargo run --example cube
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/cube`
[2020-01-22T00:03:38Z ERROR gfx_backend_vulkan]
    VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0)] : vkCreateSwapchainKHR() called with imageExtent = (800,600), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1532,1056), minImageExtent = (1532,1056), maxImageExtent = (1532,1056). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
    object info: (type: DEVICE, hndl: 94500958539040)

thread 'main' panicked at 'Timeout when acquiring next swap chain texture: ()', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::expect
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
  16: cube::framework::run::{{closure}}
             at examples/cube/../framework.rs:166
  17: winit::platform_impl::platform::sticky_exit_callback
             at /home/wmoore/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/mod.rs:697
  18: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/wmoore/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/x11/mod.rs:290
  19: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/wmoore/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/x11/mod.rs:386
  20: winit::platform_impl::platform::EventLoop<T>::run
             at /home/wmoore/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/mod.rs:644
  21: winit::event_loop::EventLoop<T>::run
             at /home/wmoore/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/event_loop.rs:148
  22: cube::framework::run
             at examples/cube/../framework.rs:127
  23: cube::main
             at examples/cube/main.rs:364
  24: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  25: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  26: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  28: std::panicking::try
             at src/libstd/panicking.rs:265
  29: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  30: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  31: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  32: main
  33: __libc_start_main
  34: _start
```

I'm not sure if this relevant but I'm running the Awesome window manager (X11) with 2 x 4K screens:

```
Screen 0: minimum 320 x 200, current 7680 x 2160, maximum 16384 x 16384
DisplayPort-0 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   3840x2160     60.00*+  29.98
HDMI-A-0 connected 3840x2160+3840+0 (normal left inverted right x axis y axis) 527mm x 296mm
   3840x2160     60.00*+  60.00    50.00    59.94    30.00    25.00    24.00    29.97    23.98

screen #0:
  dimensions:    7680x2160 pixels (1016x285 millimeters)
  resolution:    192x193 dots per inch
  depths (7):    24, 1, 4, 8, 15, 16, 32
  root window id:    0x6d3
  depth of root window:    24 planes
  number of colormaps:    minimum 1, maximum 1
  default colormap:    0x20
  default number of colormap cells:    256
  preallocated pixels:    black 0, white 16777215
  options:    backing-store WHEN MAPPED, save-unders NO
  largest cursor:    128x128
  current input event mask:    0x7a803c
    ButtonPressMask          ButtonReleaseMask        EnterWindowMask
    LeaveWindowMask          ExposureMask             StructureNotifyMask
    SubstructureNotifyMask   SubstructureRedirectMask FocusChangeMask
    PropertyChangeMask
  number of visuals:    504
```

**Comment by kvark** [comment]
Alright, so a good idea to start would be fixing that validation error. We need to clamp the requested swapchain size to the supported size range, roughly here - https://github.com/gfx-rs/wgpu/blob/c59e35e9cb8011fc616b61023034ce05ee53c6b1/wgpu-core/src/device/mod.rs#L1818
The supported size range is in `caps`.

There will be a problem as to how to communicate to the user that their requested size isn't possible to get, or alternatively, to tell what sizes are available and assert if it's out of range. But before addressing that, it would be useful to at least confirm that simply fixing the validation gets you going, at least with the basic examples.

Want to give a try fixing this locally?

**Comment by wezm** [comment]
> Want to give a try fixing this locally?

Yeah I can take a stab at it tonight.

**Comment by wezm** [comment]
So made this change to clamp the width and height, not sure if it's really right or not. I also tried a version where I changed the desc arg to a mutable reference and that yielded the same result:

```diff
diff --git a/wgpu-core/src/device/mod.rs b/wgpu-core/src/device/mod.rs
index 2627274..5f04b15 100644
--- a/wgpu-core/src/device/mod.rs
+++ b/wgpu-core/src/device/mod.rs
@@ -1815,7 +1815,22 @@ impl<F: IdentityFilter<id::SwapChainId>> Global<F> {
         let num_frames = swap_chain::DESIRED_NUM_FRAMES
             .max(*caps.image_count.start())
             .min(*caps.image_count.end());
-        let mut config = desc.to_hal(num_frames, device.features);
+
+        // Clamp width/height to within capabilities width/height
+        let mut desc = desc.clone();
+        if desc.width < caps.extents.start().width {
+            desc.width = caps.extents.start().width;
+        }
+        if desc.width > caps.extents.end().width {
+            desc.width = caps.extents.end().width;
+        }
+        if desc.height < caps.extents.start().height {
+            desc.height = caps.extents.start().height;
+        }
+        if desc.height > caps.extents.end().height {
+            desc.height = caps.extents.end().height;
+        }
+        let mut config =desc.to_hal(num_frames, device.features);
         if let Some(formats) = formats {
             assert!(
                 formats.contains(&config.format),
```

Re-running the wgpu-rs cube example still panics, but it did resolve the Vulkan validation error…

```
thread 'main' panicked at 'Timeout when acquiring next swap chain texture: ()', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by kvark** [comment]
Thank you! So it sounds like the validation error was unrelated.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!

**Comment by wezm** [comment]
Can confirm the examples now work for me.
