### ISSUE TITLE
panic: vec_map: key not present

### ISSUE THREAD

**Issue by harrisonthorne** [gfx-rs/wgpu-rs#229]
So I'm running a tutorial from https://github.com/sotrh/learn-wgpu, in the folder ./code/beginner/tutorial2-swapchain. Running `cargo run --bin tutorial2-swapchain` causes the program to open a window briefly, then crash and panic (full backtrace follows).

I'm running Arch Linux, kernel 5.4.28-1-lts. I just tested the `shadow` example in this repository, and it works.

full backtrace:

```
thread 'main' panicked at 'key not present', /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.8.1/src/lib.rs:818:9
stack backtrace:
   0:     0x55b62a34bc64 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55b62a34bc64 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55b62a34bc64 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55b62a34bc64 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55b62a36ba4c - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x55b62a349197 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x55b62a34de45 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55b62a34de45 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55b62a34de45 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x55b62a34db31 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x55b62a34e4aa - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x55b62a34e090 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x55b62a369911 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x55b62a3696a3 - core::option::expect_failed::hec9609db448f63c6
                               at src/libcore/option.rs:1191
  14:     0x55b629de1eb5 - core::option::Option<T>::expect::h19ca8650ee4b0c89
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/option.rs:347
  15:     0x55b629f02634 - <vec_map::VecMap<V> as core::ops::index::Index<usize>>::index::h133723957cf8b518
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.8.1/src/lib.rs:818
  16:     0x55b629ece325 - <wgpu_native::hub::Storage<T,I> as core::ops::index::Index<I>>::index::hf4fb0269968a5b4f
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.2/src/hub.rs:119
  17:     0x55b629ec8a91 - wgpu_native::command::command_encoder_begin_render_pass::{{closure}}::hda69a965171bc859
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.2/src/command/mod.rs:262
  18:     0x55b629dd88dd - core::option::Option<T>::map::h6cba0d4e23d04ff5
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/option.rs:450
  19:     0x55b629ec425c - wgpu_native::command::command_encoder_begin_render_pass::h45b0afb2fccd9f71
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.2/src/command/mod.rs:260
  20:     0x55b629eca029 - wgpu_command_encoder_begin_render_pass
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.2/src/command/mod.rs:741
  21:     0x55b629d9efc8 - wgpu::CommandEncoder::begin_render_pass::hfdac3f80889a1d4a
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1059
  22:     0x55b629d5e047 - tutorial2_swapchain::State::render::h5d69847055d62541
                               at code/beginner/tutorial2-swapchain/src/main.rs:77
  23:     0x55b629d4162d - tutorial2_swapchain::main::{{closure}}::hdefdeb786c718778
                               at code/beginner/tutorial2-swapchain/src/main.rs:146
  24:     0x55b629d87fcd - winit::platform_impl::platform::sticky_exit_callback::h18586e4a8384d297
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/mod.rs:697
  25:     0x55b629d59572 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::h7abdad5aaee29070
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/wayland/event_loop.rs:503
  26:     0x55b629d5b38a - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run::h4da0e410d3f25f45
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/wayland/event_loop.rs:445
  27:     0x55b629d87b51 - winit::platform_impl::platform::EventLoop<T>::run::hb4c8bd33e579c563
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/mod.rs:643
  28:     0x55b629d3f493 - winit::event_loop::EventLoop<T>::run::h38bcc791f7b91934
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/event_loop.rs:148
  29:     0x55b629d5e2fd - tutorial2_swapchain::main::h3a018437fd509016
                               at code/beginner/tutorial2-swapchain/src/main.rs:110
  30:     0x55b629d41700 - std::rt::lang_start::{{closure}}::h1ad802044fb554f7
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  31:     0x55b62a34df73 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  32:     0x55b62a34df73 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  33:     0x55b62a351dd7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  34:     0x55b62a34e950 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  35:     0x55b62a34e950 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  36:     0x55b62a34e950 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  37:     0x55b629d416d9 - std::rt::lang_start::h3f661f8b9057a0dc
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  38:     0x55b629d5e3da - main
  39:     0x7fa820a5f023 - __libc_start_main
  40:     0x55b629d3319e - _start
  41:                0x0 - <unknown>
```

**Comment by kvark** [comment]
It's weird that the call stack shows wgpu-native-0.4.2. The latest published version is 0.4.3.
Could you do `cargo update -p wgpu-native` and re-check (and post the new call stack)?

**Comment by harrisonthorne** [comment]
@kvark Same result :( New backtrace:

```
thread 'main' panicked at 'key not present', /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.8.1/src/lib.rs:818:9
stack backtrace:
   0:     0x55f178da43d4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55f178da43d4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55f178da43d4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55f178da43d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55f178dc41bc - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x55f178da1907 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x55f178da65b5 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55f178da65b5 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55f178da65b5 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x55f178da62a1 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x55f178da6c1a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x55f178da6800 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x55f178dc2081 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x55f178dc1e13 - core::option::expect_failed::hec9609db448f63c6
                               at src/libcore/option.rs:1191
  14:     0x55f17883a1f5 - core::option::Option<T>::expect::h9064030833d24fcd
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/option.rs:347
  15:     0x55f17895c2b4 - <vec_map::VecMap<V> as core::ops::index::Index<usize>>::index::hba993339ac0c2506
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.8.1/src/lib.rs:818
  16:     0x55f17892a545 - <wgpu_native::hub::Storage<T,I> as core::ops::index::Index<I>>::index::hee166701357ed4ca
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/hub.rs:119
  17:     0x55f178922b81 - wgpu_native::command::command_encoder_begin_render_pass::{{closure}}::h6dd6a157d90bd841
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:266
  18:     0x55f178836e6d - core::option::Option<T>::map::hf3785a7ea2fa54ef
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/option.rs:450
  19:     0x55f17891e39c - wgpu_native::command::command_encoder_begin_render_pass::h61e6276588709e98
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:264
  20:     0x55f178924109 - wgpu_command_encoder_begin_render_pass
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:739
  21:     0x55f1787f5fc8 - wgpu::CommandEncoder::begin_render_pass::hf76c87aff005d2b7
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1059
  22:     0x55f1787c4437 - tutorial2_swapchain::State::render::hae11cc4e0bd33e7e
                               at code/beginner/tutorial2-swapchain/src/main.rs:77
  23:     0x55f1787b315d - tutorial2_swapchain::main::{{closure}}::h3302149f516f1ac1
                               at code/beginner/tutorial2-swapchain/src/main.rs:146
  24:     0x55f1787a823d - winit::platform_impl::platform::sticky_exit_callback::h3f3ef29dd0ebbd8c
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/mod.rs:697
  25:     0x55f1787ce5a2 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::h4aeb790bff37efad
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/wayland/event_loop.rs:503
  26:     0x55f1787d03ba - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run::h3f8b591128ce7acb
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/wayland/event_loop.rs:445
  27:     0x55f1787a7f81 - winit::platform_impl::platform::EventLoop<T>::run::hcd1a652673bd59d6
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/platform_impl/linux/mod.rs:643
  28:     0x55f17878d633 - winit::event_loop::EventLoop<T>::run::h0ce93abfaa770532
                               at /home/harrisonthorne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0/src/event_loop.rs:148
  29:     0x55f1787c46ed - tutorial2_swapchain::main::h115ed5a4e3d7030b
                               at code/beginner/tutorial2-swapchain/src/main.rs:110
  30:     0x55f1787d19c0 - std::rt::lang_start::{{closure}}::hd0725e279394462a
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  31:     0x55f178da66e3 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  32:     0x55f178da66e3 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  33:     0x55f178daa547 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  34:     0x55f178da70c0 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  35:     0x55f178da70c0 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  36:     0x55f178da70c0 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  37:     0x55f1787d1999 - std::rt::lang_start::heeb1641d002d974c
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  38:     0x55f1787c47ca - main
  39:     0x7f869d65f023 - __libc_start_main
  40:     0x55f17878a19e - _start
  41:                0x0 - <unknown>
```

**Comment by kvark** [comment]
Strange. I just checked out learn-wgpu and ran that tutorial without a panic.

**Comment by harrisonthorne** [comment]
Performing a system upgrade and installing a few more packages seemed to solve the issue:

```
pacman -Syu lib32-vulkan-radeon lib32-amdvlk vulkan-headers
```

(Note: I have an AMD GPU)

Both the shadow example and the tutorial work now :) I'll close this issue since it's solved on my end and it was already working on yours.
