### ISSUE TITLE
Panic when submitting the queue a 2nd time with different command buffers.

### ISSUE THREAD

**Issue by StarArawn** [gfx-rs/wgpu-rs#255]
I might be doing some weird things, but here is a repo:
https://github.com/StarArawn/harmony

The error in full is: 
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ERROR_DEVICE_LOST)`',
```

I also get this error: 
```
thread 'main' panicked at 'key not present', 
```

Note: If you don't run the first `queue.submit` it works fine.

Stack trace:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ERROR_DEVICE_LOST)`', <::std::macros::panic macros>:5:6
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\fmt\mod.rs:1052
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:472
  10: std::panicking::begin_panic_handler
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:380
  11: std::panicking::begin_panic_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:334
  12: gfx_backend_vulkan::{{impl}}::submit<gfx_backend_vulkan::command::CommandBuffer,core::iter::adapters::flatten::FlatMap<core::slice::Iter<wgpu_core::id::Id<wgpu_core::command::CommandBuffer<gfx_backend_empty::Backend>>>, alloc::vec::Vec<gfx_backend_vulkan:
             at <::std::macros::panic macros>:5
  13: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::queue_submit<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.0\src\device\mod.rs:1540
  14: wgpu_native::device::wgpu_queue_submit
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.5.0\src\device.rs:331
  15: wgpu::Queue::submit
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.5.0\src\lib.rs:1619
  16: harmony::gui::renderer::Renderer::draw
             at .\src\gui\renderer.rs:159
  17: harmony::application::Application::run<hello_cube::AppState>
             at .\src\application.rs:154
  18: hello_cube::main::{{closure}}
             at .\examples\hello-cube.rs:69
  19: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:204
  20: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\liballoc\boxed.rs:1022
  21: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:467
  22: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:318
  23: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:305
  24: panic_unwind::__rust_maybe_catch_panic
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
  25: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:281
  26: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:394
  27: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:465
  28: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:376
  29: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:121
  30: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:106
  31: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:102
  32: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:686
  33: DefSubclassProc
  34: DefSubclassProc
  35: CallWindowProcW
  36: CallWindowProcW
  37: glPushClientAttrib
  38: CallWindowProcW
  39: DispatchMessageW
  40: IsWindowVisible
  41: KiUserCallbackDispatcher
  42: NtUserDispatchMessage
  43: DispatchMessageW
  44: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:263
  45: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:189
  46: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\event_loop.rs:148
  47: hello_cube::main
             at .\examples\hello-cube.rs:68
  48: std::rt::lang_start::{{closure}}<()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\rt.rs:67
  49: std::rt::lang_start_internal::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:52
  50: std::panicking::try::do_call<closure-0,i32>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:305
  51: panic_unwind::__rust_maybe_catch_panic
  52: std::panicking::try
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:281
  53: std::panic::catch_unwind
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panic.rs:394
  54: std::rt::lang_start_internal
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:51
  55: std::rt::lang_start<()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\rt.rs:67
  56: main
  57: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  58: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  59: BaseThreadInitThunk
  60: RtlUserThreadStart
```

2nd stack trace: 
```
thread 'main' panicked at 'key not present', C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\vec_map-0.8.1\src\lib.rs:834:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\fmt\mod.rs:1052
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:472
  10: std::panicking::begin_panic_handler
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:380
  11: core::panicking::panic_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\panicking.rs:85
  12: core::option::expect_failed
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\option.rs:1191
  13: core::option::Option<mut (wgpu_core::command::CommandBuffer<gfx_backend_vulkan::Backend>, u32)*>::expect<mut (wgpu_core::command::CommandBuffer<gfx_backend_vulkan::Backend>, u32)*>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\option.rs:347
  14: vec_map::{{impl}}::index_mut<(wgpu_core::command::CommandBuffer<gfx_backend_vulkan::Backend>, u32)>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\vec_map-0.8.1\src\lib.rs:834
  15: wgpu_core::hub::{{impl}}::index_mut<wgpu_core::command::CommandBuffer<gfx_backend_vulkan::Backend>,wgpu_core::id::Id<wgpu_core::command::CommandBuffer<gfx_backend_empty::Backend>>>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.0\src\hub.rs:92
  16: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::queue_submit<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.0\src\device\mod.rs:1444
  17: wgpu_native::device::wgpu_queue_submit
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.5.0\src\device.rs:331
  18: wgpu::Queue::submit
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.5.0\src\lib.rs:1619
  19: harmony::graphics::render_graph::RenderGraph::render
             at .\src\graphics\render_graph.rs:55
  20: harmony::application::Application::run<hello_cube::AppState>
             at .\src\application.rs:140
  21: hello_cube::main::{{closure}}
             at .\examples\hello-cube.rs:69
  22: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:204
  23: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\liballoc\boxed.rs:1022
  24: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:467
  25: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:318
  26: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:305
  27: panic_unwind::__rust_maybe_catch_panic
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
  28: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:281
  29: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:394
  30: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:465
  31: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:376
  32: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:121
  33: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:106
  34: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:102
  35: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:686
  36: DefSubclassProc
  37: DefSubclassProc
  38: CallWindowProcW
  39: CallWindowProcW
  40: glPushClientAttrib
  41: CallWindowProcW
  42: DispatchMessageW
  43: IsWindowVisible
  44: KiUserCallbackDispatcher
  45: NtUserDispatchMessage
  46: DispatchMessageW
  47: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:263
  48: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:189
  49: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\event_loop.rs:148
  50: hello_cube::main
             at .\examples\hello-cube.rs:68
  51: std::rt::lang_start::{{closure}}<()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\rt.rs:67
  52: std::rt::lang_start_internal::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:52
  53: std::panicking::try::do_call<closure-0,i32>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:305
  54: panic_unwind::__rust_maybe_catch_panic
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
  55: std::panicking::try
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:281
  56: std::panic::catch_unwind
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panic.rs:394
  57: std::rt::lang_start_internal
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:51
  58: std::rt::lang_start<()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\rt.rs:67
  59: main
  60: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  61: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  62: BaseThreadInitThunk
  63: RtlUserThreadStart
```

**Comment by kvark** [comment]
Issue is trying to submit multiple command buffers that render to the swapchain image. Our implementation doesn't like that. Let's keep the issue open to at least make this error clearer.

**Comment by cwfitzgerald** [comment]
Was this fixed recently? I seem to remember is having a conversation about it.

**Comment by kvark** [comment]
We fixed the ability to have multiple command buffers writing to the swapchain image. The problem was with figuring out the initial and final layouts, and now we are just deriving them from the `LoadOp` (`Clear` is assumed to be the first use, and `Load` for subsequent ones).
I think we still have a problem about doing multiple submits that affect the same swapchain image.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
