### ISSUE TITLE
Crashes when running examples

### ISSUE THREAD

**Issue by Coder-256** [gfx-rs/wgpu-rs#27]
I'm running Windows 10 1903 build 18917.1000 (Insider Fast) and testing on commit 76c49275cbf077bdbace96c341d4690694208834. Some of the examples have not been working properly for me. Here is what I've noticed so far:

| Example | DX11 | DX12 | Vulkan |
| ------- | ---- | ---- | ------ |
| cube | Blank | Works | Works |
| hello-triangle | Crashes | Works | Works |
| hello-compute | Incorrect | Works | Works |
| mipmap | Blank | Crashes | Works |
| msaa-line | Crashes | Crashes | Crashes |
| shadow | Blank | Works (minor glitches) | Works (minor glitches) |

GL backend build always fails:
```
   Compiling wgpu v0.2.2 (C:\Users\Jacob Greenfield\wgpu-rs)
error[E0425]: cannot find function `wgpu_instance_create_surface_from_xlib` in module `wgn`
   --> src\lib.rs:511:22
    |
511 |             id: wgn::wgpu_instance_create_surface_from_xlib(self.id, display, window),
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `wgn`

error[E0425]: cannot find function `wgpu_instance_create_surface_from_macos_layer` in module `wgn`
   --> src\lib.rs:517:22
    |
517 |             id: wgn::wgpu_instance_create_surface_from_macos_layer(self.id, layer),
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `wgn`

error[E0425]: cannot find function `wgpu_instance_create_surface_from_windows_hwnd` in module `wgn`
   --> src\lib.rs:527:22
    |
527 |             id: wgn::wgpu_instance_create_surface_from_windows_hwnd(self.id, hinstance, hwnd),
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `wgn`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `wgpu`.

To learn more, run the command again with --verbose.
```

`hello-triangle` on DX11 crash:

```
>cargo run --features dx11 --example hello-triangle
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target\debug\examples\hello-triangle.exe`
thread 'main' panicked at 'Unexpected error: OutOfPoolMemory', C:\Users\Jacob Greenfield\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-descriptor-0.3.0\src\allocator.rs:96:17
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:198
   4: std::panicking::default_hook
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:212
   5: std::panicking::rust_panic_with_hook
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:475
   6: std::panicking::continue_panic_fmt
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:382
   7: std::panicking::begin_panic_fmt
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:337
   8: rendy_descriptor::allocator::allocate_from_pool::{{closure}}<gfx_backend_dx11::Backend>
             at <::std::macros::panic macros>:9
   9: core::result::Result<(), gfx_hal::pso::descriptor::AllocationError>::map_err<(),gfx_hal::pso::descriptor::AllocationError,gfx_hal::device::OutOfMemory,closure>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\src\libcore\result.rs:522
  10: rendy_descriptor::allocator::allocate_from_pool<gfx_backend_dx11::Backend>
             at C:\Users\Jacob Greenfield\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-descriptor-0.3.0\src\allocator.rs:80
  11: rendy_descriptor::allocator::DescriptorBucket<gfx_backend_dx11::Backend>::allocate<gfx_backend_dx11::Backend>
             at C:\Users\Jacob Greenfield\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-descriptor-0.3.0\src\allocator.rs:209
  12: rendy_descriptor::allocator::DescriptorAllocator<gfx_backend_dx11::Backend>::allocate<gfx_backend_dx11::Backend,arrayvec::ArrayVec<[rendy_descriptor::allocator::DescriptorSet<gfx_backend_dx11::Backend>; 1]>>
             at C:\Users\Jacob Greenfield\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-descriptor-0.3.0\src\allocator.rs:308
  13: wgpu_native::device::device_create_bind_group
             at C:\Users\Jacob Greenfield\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\a667d50\wgpu-native\src\device.rs:1032
  14: wgpu_native::device::wgpu_device_create_bind_group
             at C:\Users\Jacob Greenfield\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\a667d50\wgpu-native\src\device.rs:1158
  15: wgpu::Device::create_bind_group
             at .\src\lib.rs:606
  16: hello_triangle::main
             at .\examples\hello-triangle\main.rs:68
  17: std::rt::lang_start::{{closure}}<()>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\src\libstd\rt.rs:64
  18: std::rt::lang_start_internal::{{closure}}
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\rt.rs:49
  19: std::panicking::try::do_call<closure,i32>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:294
  20: panic_unwind::__rust_maybe_catch_panic
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libpanic_unwind\lib.rs:82
  21: std::panicking::try
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:273
  22: std::panic::catch_unwind
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panic.rs:388
  23: std::rt::lang_start_internal
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\rt.rs:48
  24: std::rt::lang_start<()>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\src\libstd\rt.rs:64
  25: main
  26: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  27: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  28: BaseThreadInitThunk
  29: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\hello-triangle.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

`hello-compute` on DX11, incorrect output:

```
>cargo run --features dx11 --example hello-compute 1 2 3 4
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target\debug\examples\hello-compute.exe 1 2 3 4`
Times: [1, 2, 3, 4]
```

`mipmap` on DX12 crash (I think caused by [this](https://github.com/gfx-rs/gfx/blob/c8c7ee9d770745ba9ce75e10fd1bd0599eb73f49/src/backend/dx12/src/device.rs#L553)):

```
>cargo run --features dx12 --example mipmap
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target\debug\examples\mipmap.exe`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `9`', C:\Users\Jacob Greenfield\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.2.0\src\device.rs:553:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:198
   4: std::panicking::default_hook
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:212
   5: std::panicking::rust_panic_with_hook
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:475
   6: std::panicking::continue_panic_fmt
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:382
   7: std::panicking::begin_panic_fmt
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:337
   8: gfx_backend_dx12::Device::view_image_as_render_target_impl
             at C:\Users\Jacob Greenfield\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.2.0\src\device.rs:553
   9: gfx_backend_dx12::Device::view_image_as_render_target
             at C:\Users\Jacob Greenfield\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.2.0\src\device.rs:635
  10: gfx_backend_dx12::device::{{impl}}::create_image_view
             at C:\Users\Jacob Greenfield\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.2.0\src\device.rs:2327
  11: wgpu_native::device::texture_create_view
             at C:\Users\Jacob Greenfield\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\a667d50\wgpu-native\src\device.rs:784
  12: wgpu_native::device::wgpu_texture_create_default_view
             at C:\Users\Jacob Greenfield\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\a667d50\wgpu-native\src\device.rs:859
  13: wgpu::Texture::create_default_view
             at .\src\lib.rs:956
  14: mipmap::{{impl}}::init
             at .\examples\mipmap\main.rs:250
  15: mipmap::framework::run<mipmap::Example>
             at .\examples\framework.rs:112
  16: mipmap::main
             at .\examples\mipmap\main.rs:429
  17: std::rt::lang_start::{{closure}}<()>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\src\libstd\rt.rs:64
  18: std::rt::lang_start_internal::{{closure}}
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\rt.rs:49
  19: std::panicking::try::do_call<closure,i32>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:294
  20: panic_unwind::__rust_maybe_catch_panic
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libpanic_unwind\lib.rs:82
  21: std::panicking::try
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:273
  22: std::panic::catch_unwind
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panic.rs:388
  23: std::rt::lang_start_internal
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\rt.rs:48
  24: std::rt::lang_start<()>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\src\libstd\rt.rs:64
  25: main
  26: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  27: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  28: BaseThreadInitThunk
  29: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\mipmap.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

`msaa-line` on DX12 crash (the same error happens for DX11 and Vulkan too):
```
>cargo run --features dx12 --example msaa-line
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target\debug\examples\msaa-line.exe`
Press left/right arrow keys to change sample_count.
sample_count: 2
thread 'main' panicked at 'No rendering work has been submitted for the presented frame (image 0)', C:\Users\Jacob Greenfield\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\a667d50\wgpu-native\src\swap_chain.rs:217:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:198
   4: std::panicking::default_hook
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:212
   5: std::panicking::rust_panic_with_hook
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:475
   6: std::panicking::continue_panic_fmt
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:382
   7: std::panicking::begin_panic_fmt
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:337
   8: wgpu_native::swap_chain::wgpu_swap_chain_present
             at C:\Users\Jacob Greenfield\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\a667d50\wgpu-native\src\swap_chain.rs:217
   9: wgpu::{{impl}}::drop
             at .\src\lib.rs:1256
  10: core::ptr::real_drop_in_place<wgpu::SwapChainOutput>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\src\libcore\ptr\mod.rs:197
  11: msaa_line::framework::run<msaa_line::Example>
             at .\examples\framework.rs:152
  12: msaa_line::main
             at .\examples\msaa-line\main.rs:211
  13: std::rt::lang_start::{{closure}}<()>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\src\libstd\rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\rt.rs:49
  15: std::panicking::try::do_call<closure,i32>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:294
  16: panic_unwind::__rust_maybe_catch_panic
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libpanic_unwind\lib.rs:82
  17: std::panicking::try
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panicking.rs:273
  18: std::panic::catch_unwind
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\panic.rs:388
  19: std::rt::lang_start_internal
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\/src\libstd\rt.rs:48
  20: std::rt::lang_start<()>
             at /rustc/2fe7b3383c1e0a8b68f8a809be3ac21006998929\src\libstd\rt.rs:64
  21: main
  22: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  24: BaseThreadInitThunk
  25: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\msaa-line.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

**Comment by kvark** [comment]
DX11/12 backends weren't yet tested for these new examples. They are likely missing a few bits to get us going.
Thank you for submitting this issue! We'll look into fixing that ASAP.

**Comment by Coder-256** [comment]
Thanks. Here is what I've noticed so far:

| Example | DX11 | DX12 |
| ------- | ---- | ---- |
| cube | Blank | Works |
| hello-compute | Crashes | Works |
| mipmap | Blank | Crashes |
| msaa-line | Crashes | Crashes |
| shadow | Blank | Works (minor glitches) |

**Comment by kvark** [comment]
Thank you @Coder-256 , that's a lovely table! To clarify a bit more, "msaa-line" isn't supposed to work yet anywhere. There is still some MSAA plumbing to do (@rukai wanted to help with this).
As for the others - any help would be welcome. One would basically have a local override for gfx-rs repository and try to fix the panics/issues encountered. That requires some knowledge about gfx-hal, DX11/DX12, and an ability to use a graphics debugger like RenderDoc.

**Comment by kvark** [comment]
I'm going to close this in favor of #47, which is very similar but has more up-to-date status.
