### ISSUE TITLE
Panic when using a label longer than 63 bytes.

### ISSUE THREAD

**Issue by Limeth** [gfx-rs/wgpu-rs#289]
I am on version 0.5.0 of wgpu-rs and I noticed, that in `debug` mode, I am encountering the following panic:
```rust
thread 'main' panicked at 'index out of bounds: the len is 64 but the index is 66', /home/limeth/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.5.3/src/device.rs:2284:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  11: rust_begin_unwind
             at src/libstd/panicking.rs:385
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:65
  14: gfx_backend_vulkan::device::<impl gfx_backend_vulkan::Device>::set_object_name
             at /home/limeth/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.5.3/src/device.rs:2284
  15: gfx_backend_vulkan::device::<impl gfx_hal::device::Device<gfx_backend_vulkan::Backend> for gfx_backend_vulkan::Device>::set_descriptor_set_layout_name
             at /home/limeth/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.5.3/src/device.rs:2265
  16: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_bind_group_layout
             at /home/limeth/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.4/src/device/mod.rs:929
  17: wgpu::Device::create_bind_group_layout
             at /home/limeth/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.5.0/src/lib.rs:803
  18: isogame::render::GraphicsResources::new
             at src/render/mod.rs:767
  19: isogame::main
             at src/main.rs:250
  20: std::rt::lang_start::{{closure}}
             at /home/limeth/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  23: std::panicking::try
             at src/libstd/panicking.rs:274
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: main
  27: __libc_start_main
  28: _start
```

However, upon inspecting the `master` branch of the gfx crate, it seems this panic has been fixed.
https://github.com/gfx-rs/gfx/blob/master/src/backend/vulkan/src/device.rs#L2279-L2280

**Comment by kvark** [comment]
We'll make a patch that includes https://github.com/gfx-rs/gfx/pull/3214

**Comment by kvark** [comment]
Fixed in https://crates.io/crates/gfx-backend-vulkan/0.5.6
