### ISSUE TITLE
Running on Android example

### ISSUE THREAD

**Issue by vogre** [gfx-rs/wgpu-rs#313]
Trying to run the examples from the latest git `master` with naive choice of `cargo apk` approach resulted in a panic:

```
thread '<unnamed>' panicked at 'native window null', /home/vogre/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/android/mod.rs:418:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
             at ./rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/panicking.rs:397
  12: winit::platform_impl::platform::Window::raw_window_handle
             at ./home/vogre/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/android/mod.rs:418
  13: <winit::window::Window as raw_window_handle::HasRawWindowHandle>::raw_window_handle
             at ./home/vogre/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/window.rs:791
  14: <gfx_backend_vulkan::Instance as gfx_hal::Instance<gfx_backend_vulkan::Backend>>::create_surface
             at ./home/vogre/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.5.6/src/lib.rs:543
  15: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::instance_create_surface::{{closure}}
             at ./home/vogre/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/a7200bb/wgpu-core/src/instance.rs:237
  16: core::option::Option<T>::and_then
             at ./rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/option.rs:670
  17: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::instance_create_surface
             at ./home/vogre/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/a7200bb/wgpu-core/src/instance.rs:233
  18: wgpu::backend::direct::<impl wgpu::Context for wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>::instance_create_surface
             at ./home/vogre/Dev/wgpu-rs/src/backend/direct.rs:229
  19: wgpu::Instance::create_surface
             at ./home/vogre/Dev/wgpu-rs/src/lib.rs:928
  20: cube::framework::run_async::{{closure}}
             at examples/cube/../framework.rs:58
  21: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/future.rs:44
  22: futures_executor::local_pool::block_on::{{closure}}
             at ./home/vogre/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  23: futures_executor::local_pool::run_executor::{{closure}}
             at ./home/vogre/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  24: std::thread::local::LocalKey<T>::try_with
             at ./rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/local.rs:262
  25: std::thread::local::LocalKey<T>::with
             at ./rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/local.rs:239
  26: futures_executor::local_pool::run_executor
             at ./home/vogre/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  27: futures_executor::local_pool::block_on
             at ./home/vogre/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  28: cube::framework::run
             at examples/cube/../framework.rs:198
  29: cube::main
             at examples/cube/main.rs:365
  30: ndk_glue::init::{{closure}}
             at ./home/vogre/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-glue-0.1.0/src/lib.rs:195
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Is this the right way to go, or a different approach is needed?

**Comment by kvark** [comment]
It looks to be panicking inside the `RawWindowHandle` implementation for your window.
I'll ask folks on the chat to see what's missing here.

**Comment by TheRawMeatball** [comment]
I'm pretty sure this is rust-windowing/winit#1588

**Comment by TheRawMeatball** [comment]
On another front, this is not the only issue. After fixing this, here is the relevant logcat output I get with my slightly modified version of the hello-triangle example:
```
06-18 09:37:16.608  2134  2157 I RustStdoutStderr: -----------------------------------------RUST START------------------------------------------------
06-18 09:37:16.608  2134  2157 I RustStdoutStderr: Waiting for NativeScreen
06-18 09:37:16.627  2134  2157 I RustStdoutStderr: NativeScreen Found:RwLockReadGuard { lock: RwLock { data: Some(NativeWindow { ptr: 0x73639f4010 }) } }
06-18 09:37:16.630  2134  2158 D vulkan  : searching for layers in '/data/app/rust.example.hello_triangle-Sq7qBU-XxxSKvKk6XWtvDQ==/lib/arm64'
06-18 09:37:16.631  2134  2158 D vulkan  : searching for layers in '/data/app/rust.example.hello_triangle-Sq7qBU-XxxSKvKk6XWtvDQ==/base.apk!/lib/arm64-v8a'
06-18 09:37:16.633  2134  2158 I AdrenoVK: QUALCOMM build          : 033a5b0, I0e419467bc
06-18 09:37:16.633  2134  2158 I AdrenoVK: Build Date              : 03/11/20
06-18 09:37:16.633  2134  2158 I AdrenoVK: Shader Compiler Version : EV031.27.05.01
06-18 09:37:16.633  2134  2158 I AdrenoVK: Local Branch            : 
06-18 09:37:16.633  2134  2158 I AdrenoVK: Remote Branch           : refs/tags/AU_LINUX_ANDROID_LA.UM.8.3.R1.10.00.00.520.058
06-18 09:37:16.633  2134  2158 I AdrenoVK: Remote Branch           : NONE
06-18 09:37:16.633  2134  2158 I AdrenoVK: Reconstruct Branch      : NOTHING
06-18 09:37:16.633  2134  2158 I AdrenoVK: Build Config            : S P 8.0.11 AArch64
06-18 09:37:16.634  2134  2157 I RustStdoutStderr: surface made
06-18 09:37:16.636  2134  2157 I RustStdoutStderr: adapter made
06-18 09:37:16.637  2134  2157 I RustStdoutStderr: [2020-06-18T06:37:16Z ERROR gfx_backend_vulkan] [vulkan] invalid vkGetDeviceProcAddr(0x73683eb2c0, "vkGetPhysicalDevicePresentRectanglesKHR") call
06-18 09:37:16.637  2134  2157 I RustStdoutStderr: device and queue made
06-18 09:37:16.638  1366  1522 I ActivityTaskManager: Displayed rust.example.hello_triangle/android.app.NativeActivity: +172ms
06-18 09:37:16.639  2134  2157 I RustStdoutStderr: shader modules made
06-18 09:37:16.639  2134  2157 I RustStdoutStderr: pipeline layout made
06-18 09:37:16.644  2134  2157 I RustStdoutStderr: pipeline made
06-18 09:37:16.644  2134  2157 I RustStdoutStderr: descriptor made
06-18 09:37:16.645  2134  2157 I RustStdoutStderr: [2020-06-18T06:37:16Z ERROR gfx_backend_vulkan] [vulkan] invalid vkGetDeviceProcAddr(0x73683eb2c0, "vkGetPhysicalDevicePresentRectanglesKHR") call
06-18 09:37:16.646   541   541 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/default in either framework or device manifest.
06-18 09:37:16.647  2134  2158 W Gralloc3: mapper 3.x is not supported
06-18 09:37:16.650  2134  2157 I RustStdoutStderr: swapchain made
06-18 09:37:16.650  2134  2157 I RustStdoutStderr: -----------------------ENTERING EVENT LOOP-------------------------------
```

And here is my slightly modified (and outdated) version of the hello-triangle example:
```
#[cfg(target_os = "android")]
ndk_glue::ndk_glue!(main);

use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::Window,
};

async fn run(event_loop: EventLoop<()>, window: Window, swapchain_format: wgpu::TextureFormat) {

    #[cfg(target_os = "android")]
    {
        println!("Waiting for NativeScreen");
        loop
        {
            match ndk_glue::native_window().as_ref() {
                Some(_) => 
                {
                    println!("NativeScreen Found:{:?}", ndk_glue::native_window());
                    break;
                },
                None => ()
            }
        }
    }

    let size = window.inner_size();
    let instance = wgpu::Instance::new();
    let surface = unsafe { instance.create_surface(&window) };

    println!("size:{:?}", size);

    println!("{:?}", (&window as &dyn raw_window_handle::HasRawWindowHandle).raw_window_handle());

    println!("surface made");

    let adapter = instance
        .request_adapter(
            &wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::Default,
                compatible_surface: Some(&surface),
            },
            wgpu::UnsafeExtensions::disallow(),
            wgpu::BackendBit::PRIMARY,
        )
        .await
        .unwrap();
    
    println!("adapter made");

    let (device, queue) = adapter
        .request_device(
            &wgpu::DeviceDescriptor {
                extensions: wgpu::Extensions::empty(),
                limits: wgpu::Limits::default(),
                shader_validation: true,
            },
            None,
        )
        .await
        .unwrap();

    println!("device and queue made"); //{:?} {:?}", device, queue);

    let vs = include_bytes!("shader.vert.spv");
    let vs_module =
        device.create_shader_module(&wgpu::read_spirv(std::io::Cursor::new(&vs[..])).unwrap());

    let fs = include_bytes!("shader.frag.spv");
    let fs_module =
        device.create_shader_module(&wgpu::read_spirv(std::io::Cursor::new(&fs[..])).unwrap());

    println!("shader modules made");

    let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        bind_group_layouts: &[],
    });

    println!("pipeline layout made");

    let render_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        layout: &pipeline_layout,
        vertex_stage: wgpu::ProgrammableStageDescriptor {
            module: &vs_module,
            entry_point: "main",
        },
        fragment_stage: Some(wgpu::ProgrammableStageDescriptor {
            module: &fs_module,
            entry_point: "main",
        }),
        rasterization_state: Some(wgpu::RasterizationStateDescriptor {
            front_face: wgpu::FrontFace::Ccw,
            cull_mode: wgpu::CullMode::None,
            depth_bias: 0,
            depth_bias_slope_scale: 0.0,
            depth_bias_clamp: 0.0,
        }),
        primitive_topology: wgpu::PrimitiveTopology::TriangleList,
        color_states: &[wgpu::ColorStateDescriptor {
            format: swapchain_format,
            color_blend: wgpu::BlendDescriptor::REPLACE,
            alpha_blend: wgpu::BlendDescriptor::REPLACE,
            write_mask: wgpu::ColorWrite::ALL,
        }],
        depth_stencil_state: None,
        vertex_state: wgpu::VertexStateDescriptor {
            index_format: wgpu::IndexFormat::Uint16,
            vertex_buffers: &[],
        },
        sample_count: 1,
        sample_mask: !0,
        alpha_to_coverage_enabled: false,
    });

    println!("pipeline made");

    let mut sc_desc = wgpu::SwapChainDescriptor {
        usage: wgpu::TextureUsage::OUTPUT_ATTACHMENT,
        format: swapchain_format,
        width: size.width,
        height: size.height,
        present_mode: wgpu::PresentMode::Mailbox,
    };

    println!("descriptor made");
    
    let mut swap_chain = device.create_swap_chain(&surface, &sc_desc);

    println!("swapchain made");

    println!("-----------------------ENTERING EVENT LOOP-------------------------------");

    event_loop.run(move |event, _, control_flow| {
        // force ownership by the closure
        let _ = (
            &instance,
            &adapter,
            &vs_module,
            &fs_module,
            &pipeline_layout,
        );

        *control_flow = ControlFlow::Poll;
        match event {
            Event::WindowEvent {
                event: WindowEvent::Resized(size),
                ..
            } => {
                sc_desc.width = size.width;
                sc_desc.height = size.height;
                swap_chain = device.create_swap_chain(&surface, &sc_desc);
            }
            Event::RedrawRequested(_) => {
                let frame = swap_chain
                    .get_next_frame()
                    .expect("Failed to acquire next swap chain texture")
                    .output;
                let mut encoder =
                    device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
                {
                    let mut rpass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                        color_attachments: &[wgpu::RenderPassColorAttachmentDescriptor {
                            attachment: &frame.view,
                            resolve_target: None,
                            load_op: wgpu::LoadOp::Clear,
                            store_op: wgpu::StoreOp::Store,
                            clear_color: wgpu::Color::GREEN,
                        }],
                        depth_stencil_attachment: None,
                    });
                    rpass.set_pipeline(&render_pipeline);
                    rpass.draw(0..3, 0..1);
                }

                queue.submit(Some(encoder.finish()));
            }
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => *control_flow = ControlFlow::Exit,
            _ => {}
        }
    });
}

pub fn main() {
    let event_loop = EventLoop::new();
    let window = winit::window::Window::new(&event_loop).unwrap();
    #[cfg(not(target_arch = "wasm32"))]
    {
        env_logger::init();
        // Temporarily avoid srgb formats for the swapchain on the web

        println!("-----------------------------------------RUST START------------------------------------------------");

        futures::executor::block_on(run(event_loop, window, wgpu::TextureFormat::Rgba8Unorm));
    }
    #[cfg(target_arch = "wasm32")]
    {
        std::panic::set_hook(Box::new(console_error_panic_hook::hook));
        console_log::init().expect("could not initialize logger");
        use winit::platform::web::WindowExtWebSys;
        // On wasm, append the canvas to the document body
        web_sys::window()
            .and_then(|win| win.document())
            .and_then(|doc| doc.body())
            .and_then(|body| {
                body.append_child(&web_sys::Element::from(window.canvas()))
                    .ok()
            })
            .expect("couldn't append canvas to document body");
        wasm_bindgen_futures::spawn_local(run(event_loop, window, wgpu::TextureFormat::Bgra8Unorm));
    }
}
```

I have a feeling that the pointers being diffrent in `RwLockReadGuard` and `vkGetDeviceProcAddr` has something to do with it, but I can't prove much...

**Comment by kvark** [comment]
Thank you for the update! I believe this is an upstream issue in https://github.com/MaikKlein/ash/issues/307

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
