### ISSUE TITLE
Labels cannot be more than 63 in length

### ISSUE THREAD

**Issue by Uriopass** [gfx-rs/wgpu-rs#327]
Trying to make a long label makes the rather cryptic error
```
thread 'main' panicked at 'index out of bounds: the len is 64 but the index is 95', C:\Users\xxxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.5.2\src\device.rs:2284:13
```
which corresponds to
```rust
            // Append a null terminator to the string while avoiding allocating memory
            static mut NAME_BUF: [u8; 64] = [0u8; 64];
            std::ptr::copy_nonoverlapping(
                name.as_ptr(),
                &mut NAME_BUF[0],
                name.len().min(NAME_BUF.len()),
            );
            NAME_BUF[name.len()] = 0;
```
Aka making a null terminated string out of the label.

I don't know at which point in the chain wgpu-rs <-> wgpu <-> gfx-backend-vulkan to make this issue but I wish there were some checks at some point, or maybe some documentation somewhere about this. Or even just that the label was cut at 64 before sending it to wgpu.

Cleaned stacktrace:
```rust
stack backtrace:
13: gfx_backend_vulkan::Device::set_object_name
             at C:\Users\xxxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.5.2\src\device.rs:2284
  14: gfx_backend_vulkan::device::{{impl}}::set_descriptor_set_layout_name
             at C:\Users\xxxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.5.2\src\device.rs:2270
  15: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_bind_group_layout<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
             at C:\Users\xxxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.3\src\device\mod.rs:928
  16: wgpu::Device::create_bind_group_layout
             at C:\Users\xxxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.5.0\src\lib.rs:803
```

**Comment by kvark** [comment]
This is fixed in the Vulkan backend. Please do `cargo update -p gfx-backend-vulkan`.

**Comment by Uriopass** [comment]
Oops, sorry. Thank you ! Didn't think of updating
