### ISSUE TITLE
Examples aren't working

### ISSUE THREAD

**Issue by BrandonDyer64** [gfx-rs/wgpu-rs#415]
I don't know what specific issue is causing them not to work, but running `cargo run --example hello-triangle` gives a black screen followed by an immediate crash.

System:
Memory: 31.2 GiB
Processor: Intel® Core™ i7-9700K CPU @ 3.60GHz × 8
GPU: GeForce RTX 2080 SUPER/PCIe/SSE2
GPU Driver: nvidia-driver-440
OS: Ubuntu 20.04 LTS
Gnome: 3.36.2
Windowing: X11

Branch: master

Errors:
```
[2020-06-28T12:52:27Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2020-06-28T12:52:27Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2020-06-28T12:52:27Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2020-06-28T12:52:27Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2020-06-28T12:52:27Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
thread 'main' panicked at 'Failed to focus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linŭ/x11/event_processor.rs:878:25
```

Backtrace:

```
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: core::result::Result<T,E>::expect
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/result.rs:961
  15: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linŭ/x11/event_processor.rs:878
  16: winit::platform_impl::platform::x11::EventLoop<T>::drain_events
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linŭ/x11/mod.rs:405
  17: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linŭ/x11/mod.rs:282
  18: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linŭ/x11/mod.rs:390
  19: winit::platform_impl::platform::EventLoop<T>::run
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linŭ/mod.rs:645
  20: winit::event_loop::EventLoop<T>::run
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149
  21: hello_triangle::run::{{closure}}
             at examples/hello-triangle/main.rs:83
  22: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/future.rs:44
  23: futures_executor::local_pool::block_on::{{closure}}
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  24: futures_executor::local_pool::run_executor::{{closure}}
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  25: std::thread::local::LocalKey<T>::try_with
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/local.rs:262
  26: std::thread::local::LocalKey<T>::with
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/local.rs:239
  27: futures_executor::local_pool::run_executor
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  28: futures_executor::local_pool::block_on
             at /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  29: hello_triangle::main
             at examples/hello-triangle/main.rs:148
  30: std::rt::lang_start::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  31: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  32: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  34: std::panicking::try
             at src/libstd/panicking.rs:281
  35: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  36: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  37: std::rt::lang_start
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  38: main
  39: __libc_start_main
  40: _start
```

Same error occurs on branch v0.5

**Comment by rukai** [comment]
do you get the same error when running this winit example: https://github.com/rust-windowing/winit/blob/master/examples/window.rs

**Comment by BrandonDyer64** [comment]
Nope. Seems to run fine

**Comment by kvark** [comment]
I had this issue on a linux laptop with NV GPU: https://dev.getsol.us/T6335
It's a problem with Intel + NV on linux in general with regards to Vulkan, it's not specific to wgpu-rs.
You can verify by trying to run the [Ash](https://github.com/MaikKlein/ash/) examples.

Fortunately, there is a workaround mentioned in the issue. You can force `VK_ICD_FILENAMES` from your bash script to always point to NVidia. I haven't found a way to make Intel Vulkan work on my machine.

Closing as this isn't something we can help with, it's a system problem. Please re-open otherwise!

**Comment by BrandonDyer64** [comment]
It worked! Thank you!
