### ISSUE TITLE
multithreaded_compute test fails with metal

### ISSUE THREAD

**Issue by paulkernfeld** [gfx-rs/wgpu-rs#42]
On OSX, I observe:

```
[18:20]% cargo test --features metal                                                                                      paul@compy386:~/repos/wgpu-rs on capture -> origin/capture
   Compiling wgpu v0.2.2 (/Users/paul/repos/wgpu-rs)
warning: constant item is never used: `OPENGL_TO_WGPU_MATRIX`
 --> examples/msaa-line/../framework.rs:4:1
  |
4 | / pub const OPENGL_TO_WGPU_MATRIX: cgmath::Matrix4<f32> = cgmath::Matrix4::new(
5 | |     1.0, 0.0, 0.0, 0.0,
6 | |     0.0, -1.0, 0.0, 0.0,
7 | |     0.0, 0.0, 0.5, 0.0,
8 | |     0.0, 0.0, 0.5, 1.0,
9 | | );
  | |__^
  |
  = note: #[warn(dead_code)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 10.62s
     Running target/debug/deps/wgpu-b82b9f440a8489f5

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/multithreaded_compute-312014e85c62f80f

running 1 test
test multithreaded_compute ... FAILED

failures:

---- multithreaded_compute stdout ----
thread 'multithreaded_compute' panicked at 'A thread never completed.: Timeout', src/libcore/result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:827
  10: multithreaded_compute::multithreaded_compute
             at tests/multithreaded_compute.rs:102
  11: multithreaded_compute::multithreaded_compute::{{closure}}
             at tests/multithreaded_compute.rs:3
  12: core::ops::function::FnOnce::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  15: test::run_test::run_test_inner::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
             at src/libtest/lib.rs:1468


failures:
    multithreaded_compute

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test multithreaded_compute'
```

I noticed that calling `device.poll` before `tx.send` caused the test to pass.

**Comment by paulkernfeld** [comment]
Actually, this test sometimes passes and sometimes fails on my system.
