### ISSUE TITLE
OS X error in wgpu::Adapter::request_device and/or device_create_render_pipeline

### ISSUE THREAD

**Issue by guidorice** [gfx-rs/wgpu-rs#429]
I am trying to run some of the examples from https://github.com/sotrh/learn-wgpu on my Mac OS X machine, and running into some errors. I attempted to install the vulkan sdk and compatibility layer but not sure if I did it correctly or not. There are a couple of different errors and stacktraces, shown in the issue over there:

https://github.com/sotrh/learn-wgpu/issues/63

Apologies for the cross-post!

**Comment by kvark** [comment]
Does learn-wgpu example enable env_logger? Could you run this with `RUST_LOG=gfx_backend_metal=debug`?

**Comment by kvark** [comment]
also, with `METAL_DEVICE_WRAPPER_TYPE=1` environment!

**Comment by guidorice** [comment]
> Does learn-wgpu example enable env_logger?

@kvark no it does not enable `env_logger`, but just now, I added env_logger to Cargo.toml and `env_logger::init();` in main.rs. Also trying all the environment vars mentioned. Now it's printing ` Metal API Validation Enabled` so that's good?

```
env VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation RUST_BACKTRACE=full METAL_DEVICE_WRAPPER_TYPE=1 RUST_LOG=gfx_backend_metal=debug cargo run --manifest-path code/intermediate/tutorial11-normals/Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/tutorial11-normals`
2020-07-09 14:05:31.726 tutorial11-normals[42521:973190] Metal API Validation Enabled
thread 'main' panicked at 'internal error: entered unreachable code', /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.5.0/src/device.rs:174:5
stack backtrace:
   0:        0x10360ef8f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ad47541fb823094
   1:        0x10363204e - core::fmt::write::he23e9bd6497f06c3
   2:        0x10360c237 - std::io::Write::write_fmt::h91528f1131e6004e
   3:        0x103610ffa - std::panicking::default_hook::{{closure}}::h1983f014a45a477e
   4:        0x103610d3c - std::panicking::default_hook::hb0d9b93b5be8b120
   5:        0x1036115c8 - std::panicking::rust_panic_with_hook::h9f3faafe0983de5c
   6:        0x1036405d6 - std::panicking::begin_panic::h14956f4780ea73d1
   7:        0x102d5b9ef - wgpu_adapter_request_device
   8:        0x1025ff3cc - wgpu::Adapter::request_device::{{closure}}::haea93dcd978a477b
   9:        0x1025d2853 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h56ba9dc14161dbcd
  10:        0x1025f43d9 - tutorial11_normals::State::new::{{closure}}::h8e9145dce111cc99
  11:        0x1025d293c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb8e6cc557cfb58d9
  12:        0x1025f81ef - futures_executor::local_pool::block_on::{{closure}}::h86694c5e294a3eb6
  13:        0x1025f7fce - futures_executor::local_pool::run_executor::{{closure}}::h21ae9cfb55ffa961
  14:        0x1025d3e6a - std::thread::local::LocalKey<T>::try_with::h693762379ed5462d
  15:        0x1025d3d53 - std::thread::local::LocalKey<T>::with::hf70181fd9ff44726
  16:        0x1025f7ef2 - futures_executor::local_pool::run_executor::h27684338e32ccb8e
  17:        0x1025f815e - futures_executor::local_pool::block_on::hbaa6b9227107fac0
  18:        0x1025eac7a - tutorial11_normals::main::hecd1f32154c636d8
  19:        0x1025febee - std::rt::lang_start::{{closure}}::hb5680d054672a23a
  20:        0x1036119f9 - std::rt::lang_start_internal::h795af50241e12334
  21:        0x1025febd1 - std::rt::lang_start::h4a607b770687a0a7
  22:        0x1025ead92 - main
```

**Comment by kvark** [comment]
You are running with Vulkan feature. Could you run without it, so that Metal is used?

**Comment by guidorice** [comment]
@kvark ahah!  now there is a bunch of diagnostic info printing.

> [2020-07-09T20:15:13Z ERROR gfx_backend_metal::device] PSO creation failed: Link failed: The type of fragment input user(locn0) does not match the type of the corresponding vertex shader output    

Full log attached!

[tutorial11-normals-wgpu-validation.log.gz](https://github.com/gfx-rs/wgpu-rs/files/4899301/tutorial11-normals-wgpu-validation.log.gz)

**Comment by guidorice** [comment]
Here is the source also: https://github.com/sotrh/learn-wgpu/tree/master/code/intermediate/tutorial11-normals

**Comment by kvark** [comment]
The log actually tells you pretty explicitly what's wrong there. In VS you have `float4 v_color [[user(locn0)]];`, while in FS you have `float3 v_color [[user(locn0)]];`. That gives you a clear way to solve/work around it.

Technically, in SPIR-V it's allowed that you'd only use the `vec3` portion. But Metal doesn't like that, and neither does WebGPU now.

We are working on validating the shaders properly on our side, so that these kinds of errors are shown clearly and don't reach the driver. This is a heavy WIP. Sorry about the inconvenience!

**Comment by kvark** [comment]
Filed https://github.com/sotrh/learn-wgpu/pull/70 to fix that one

**Comment by guidorice** [comment]
@kvark thanks so much! very awesome 👍

**Comment by rybertm** [comment]
I'm having the same issue when trying call `wgpu::Adapter::request_device` even in the hello-triangle example with `vulkan-portability` feature on. Using the metal backend doesn't show any error even with `RUST_LOG=gfx_backend_metal=debug` and `METAL_DEVICE_WRAPPER_TYPE=1` set.

`vulkan-portability` log:
```
thread 'main' panicked at 'internal error: entered unreachable code', 
/Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:550:25
stack backtrace:
   0:        0x100a92784 - std::backtrace_rs::backtrace::libunwind::trace::he9497f4525a08d2b
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:        0x100a92784 - std::backtrace_rs::backtrace::trace_unsynchronized::h10a0a59d96f4a16b
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:        0x100a92784 - std::sys_common::backtrace::_print_fmt::h6fd8fbf82b7783c5
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/sys_common/backtrace.rs:79
   3:        0x100a92784 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfb2db7374ccd4d34
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/sys_common/backtrace.rs:58
   4:        0x100ab038c - core::fmt::write::h7e381316a10f5e82
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/core/src/fmt/mod.rs:1117
   5:        0x100a90509 - std::io::Write::write_fmt::h53862e22ed93af5e
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/io/mod.rs:1510
   6:        0x100a941b5 - std::sys_common::backtrace::_print::h5642011e0f38c919
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/sys_common/backtrace.rs:61
   7:        0x100a941b5 - std::sys_common::backtrace::print::hbcc5d5a374cdc250
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/sys_common/backtrace.rs:48
   8:        0x100a941b5 - std::panicking::default_hook::{{closure}}::h1a87f1c0565a051b
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:200
   9:        0x100a93ef2 - std::panicking::default_hook::he29ab2038604c86f
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:219
  10:        0x100a94755 - std::panicking::rust_panic_with_hook::h9dab6d214201c5da
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:569
  11:        0x1006b27a4 - std::panicking::begin_panic::{{closure}}::h559c4609a48e8a7f
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:498
  12:        0x1006b2558 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e1eb044c5ea14a0
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:153
  13:        0x100ac0522 - std::panicking::begin_panic::hc74fdde32f1bb172
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:497
  14:        0x10029c583 - <wgpu::backend::direct::Context as wgpu::Context>::adapter_request_device::h32ea5745c66b8397
                               at /Users/robertbroketa/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:550
  15:        0x1003f9b8f - wgpu::Adapter::request_device::h6302906f8dc7153b
                               at /Users/robertbroketa/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/lib.rs:1348
  16:        0x10001d089 - chaos_game::run::{{closure}}::h2750f625a9be298d
                               at /Users/robertbroketa/Documents/dev/Rust/chaos_game/src/main.rs:21
  17:        0x10001f540 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9baa2c374c4097b1
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:78
  18:        0x10002b5d0 - futures_executor::local_pool::block_on::{{closure}}::h057f10deab0db573
                               at /Users/robertbroketa/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  19:        0x10002b442 - futures_executor::local_pool::run_executor::{{closure}}::h6f5762ac66013426
                               at /Users/robertbroketa/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  20:        0x10000dca1 - std::thread::local::LocalKey<T>::try_with::h865e6d7a01c81742
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:267
  21:        0x10000dbc5 - std::thread::local::LocalKey<T>::with::h73041a66723269c3
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:243
  22:        0x10002b3a3 - futures_executor::local_pool::run_executor::h8acd472f94955fe2
                               at /Users/robertbroketa/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  23:        0x10002b54d - futures_executor::local_pool::block_on::he28c191968991683
                               at /Users/robertbroketa/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  24:        0x10001fc52 - chaos_game::main::h3325284cf75dae83
                               at /Users/robertbroketa/Documents/dev/Rust/chaos_game/src/main.rs:141
  25:        0x10000882e - core::ops::function::FnOnce::call_once::h94b9982e66444af1
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:233
  26:        0x10000aee1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0ff4449f98994aad
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  27:        0x100002984 - std::rt::lang_start::{{closure}}::ha239dc3bdd756d9d
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66
  28:        0x100a94a48 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hdadc43748186d6df
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/core/src/ops/function.rs:265
  29:        0x100a94a48 - std::panicking::try::do_call::h406c54ffe57091dd
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:373
  30:        0x100a94a48 - std::panicking::try::hdba70b2e71b1fbd6
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:337
  31:        0x100a94a48 - std::panic::catch_unwind::h499f8b48272a4f5e
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panic.rs:394
  32:        0x100a94a48 - std::rt::lang_start_internal::h3a85459a31d0467d
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/rt.rs:51
  33:        0x100002961 - std::rt::lang_start::h9d55d3d8329fb781
                               at /Users/robertbroketa/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65
  34:        0x10001fce2 - _main
VUID-vkDestroyInstance-instance-00629(ERROR / SPEC): msgNum: -1958900200 - 
Validation Error: [ VUID-vkDestroyInstance-instance-00629 ] Object 0: handle = 0x106854400, 
type = VK_OBJECT_TYPE_INSTANCE; Object 1: handle = 0x20000000002, 
type = VK_OBJECT_TYPE_SURFACE_KHR; | MessageID = 0x8b3d8e18 | OBJ ERROR : 
For VkInstance 0x106854400[], VkSurfaceKHR 0x20000000002[] has not been destroyed. 
The Vulkan spec states: All child objects created using instance must have been destroyed prior to destroying 
instance (https://vulkan.lunarg.com/doc/view/1.2.148.0/mac/1.2-extensions/vkspec.html#VUID-vkDestroyInstance-instance-00629)
    Objects: 2
        [0] 0x106854400, type: 1, name: NULL
        [1] 0x20000000002, type: 1000000000, name: NULL
```
Note that the instance is still valid when running `wgpu::Adapter::request_device`.

**Comment by kvark** [comment]
@rybertm this is #575, which is still open

**Comment by rybertm** [comment]
@kvark, my bad, I first commented here but since it didn't reopen the issue I created a new one, wasn't sure how to proceed.

**Comment by kvark** [comment]
no worries, I just realized it was also yours. Thank you for filing!
I thought we already had that reported somewhere, but apparently no other bugs filed.
I think this is easy to fix though. PRs welcome!
