### ISSUE TITLE
MacOS vulkan-portability feature panics in wgpu::Adapter::request_device

### ISSUE THREAD

**Issue by rybertm** [gfx-rs/wgpu-rs#575]
Calling `wgpu::Adapter::request_device` in the hello-triangle example with `vulkan-portability` feature on panics. Using the metal backend doesn't show any error even with `RUST_LOG=gfx_backend_metal=debug` and `METAL_DEVICE_WRAPPER_TYPE=1` set.

`vulkan-portability` log:
```
VUID-vkDestroyInstance-instance-00629(ERROR / SPEC): msgNum: -1958900200 - 
Validation Error: [ VUID-vkDestroyInstance-instance-00629 ] Object 0: handle = 0x106854400, 
type = VK_OBJECT_TYPE_INSTANCE; Object 1: handle = 0x20000000002, 
type = VK_OBJECT_TYPE_SURFACE_KHR; | MessageID = 0x8b3d8e18 | OBJ ERROR : 
For VkInstance 0x106854400[], VkSurfaceKHR 0x20000000002[] has not been destroyed. 
The Vulkan spec states: All child objects created using instance must have been destroyed prior to destroying 
instance (https://vulkan.lunarg.com/doc/view/1.2.148.0/mac/1.2-extensions/vkspec.html#VUID-vkDestroyInstance-instance-00629)
    Objects: 2
        [0] 0x106854400, type: 1, name: NULL
        [1] 0x20000000002, type: 1000000000, name: NULL
```
Note that the instance is still valid when calling `wgpu::Adapter::request_device`.

Backtrace:
```
thread 'main' panicked at 'internal error: entered unreachable code', 
/Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:550:25
stack backtrace:
   0:        0x100a92784 - std::backtrace_rs::backtrace::libunwind::trace::he9497f4525a08d2b
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:        0x100a92784 - std::backtrace_rs::backtrace::trace_unsynchronized::h10a0a59d96f4a16b
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:        0x100a92784 - std::sys_common::backtrace::_print_fmt::h6fd8fbf82b7783c5
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/sys_common/backtrace.rs:79
   3:        0x100a92784 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfb2db7374ccd4d34
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/sys_common/backtrace.rs:58
   4:        0x100ab038c - core::fmt::write::h7e381316a10f5e82
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/core/src/fmt/mod.rs:1117
   5:        0x100a90509 - std::io::Write::write_fmt::h53862e22ed93af5e
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/io/mod.rs:1510
   6:        0x100a941b5 - std::sys_common::backtrace::_print::h5642011e0f38c919
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/sys_common/backtrace.rs:61
   7:        0x100a941b5 - std::sys_common::backtrace::print::hbcc5d5a374cdc250
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/sys_common/backtrace.rs:48
   8:        0x100a941b5 - std::panicking::default_hook::{{closure}}::h1a87f1c0565a051b
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:200
   9:        0x100a93ef2 - std::panicking::default_hook::he29ab2038604c86f
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:219
  10:        0x100a94755 - std::panicking::rust_panic_with_hook::h9dab6d214201c5da
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:569
  11:        0x1006b27a4 - std::panicking::begin_panic::{{closure}}::h559c4609a48e8a7f
                               at /Users//.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:498
  12:        0x1006b2558 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e1eb044c5ea14a0
                               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:153
  13:        0x100ac0522 - std::panicking::begin_panic::hc74fdde32f1bb172
                               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:497
  14:        0x10029c583 - <wgpu::backend::direct::Context as wgpu::Context>::adapter_request_device::h32ea5745c66b8397
                               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:550
  15:        0x1003f9b8f - wgpu::Adapter::request_device::h6302906f8dc7153b
                               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/lib.rs:1348
  16:        0x10001d089 - proj::run::{{closure}}::h2750f625a9be298d
                               at /Users/user/Documents/dev/Rust/proj/src/main.rs:21
  17:        0x10001f540 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9baa2c374c4097b1
                               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:78
  18:        0x10002b5d0 - futures_executor::local_pool::block_on::{{closure}}::h057f10deab0db573
                               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  19:        0x10002b442 - futures_executor::local_pool::run_executor::{{closure}}::h6f5762ac66013426
                               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  20:        0x10000dca1 - std::thread::local::LocalKey<T>::try_with::h865e6d7a01c81742
                               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:267
  21:        0x10000dbc5 - std::thread::local::LocalKey<T>::with::h73041a66723269c3
                               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:243
  22:        0x10002b3a3 - futures_executor::local_pool::run_executor::h8acd472f94955fe2
                               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  23:        0x10002b54d - futures_executor::local_pool::block_on::he28c191968991683
                               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  24:        0x10001fc52 - proj::main::h3325284cf75dae83
                               at /Users/user/Documents/dev/Rust/proj/src/main.rs:141
  25:        0x10000882e - core::ops::function::FnOnce::call_once::h94b9982e66444af1
                               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:233
  26:        0x10000aee1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0ff4449f98994aad
                               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  27:        0x100002984 - std::rt::lang_start::{{closure}}::ha239dc3bdd756d9d
                               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66
  28:        0x100a94a48 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hdadc43748186d6df
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/core/src/ops/function.rs:265
  29:        0x100a94a48 - std::panicking::try::do_call::h406c54ffe57091dd
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:373
  30:        0x100a94a48 - std::panicking::try::hdba70b2e71b1fbd6
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panicking.rs:337
  31:        0x100a94a48 - std::panic::catch_unwind::h499f8b48272a4f5e
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/panic.rs:394
  32:        0x100a94a48 - std::rt::lang_start_internal::h3a85459a31d0467d
                               at /rustc/9b88e0a8667040452a94fda8548f0f5f0f801f90/library/std/src/rt.rs:51
  33:        0x100002961 - std::rt::lang_start::h9d55d3d8329fb781
                               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65
  34:        0x10001fce2 - _main
```

**Comment by rybertm** [comment]
https://github.com/gfx-rs/wgpu-rs/blob/55cafa398868998d1c14620111208d92f5cda9d5/Cargo.toml#L23 sets the `gfx-backend-vulkan` feature inside `wgpu/wgpu-core` but in this crate only `vulkan-portability` gets set, so when `gfx_select!` is expanded it checks for `gfx-backend-vulkan`, which is not present in `wgpu-rs`: https://github.com/gfx-rs/wgpu-rs/blob/55cafa398868998d1c14620111208d92f5cda9d5/src/backend/direct.rs#L593-L595

As for fixing, I could add a `gfx-backend-vulkan` dependency to the `vulkan-portability` feature as well as add it to macos targets, but I don't know if it could break in other unix systems @kvark.

**Comment by kvark** [comment]
Yes, that sounds appropriate! Please make that PR.
Note that wgpu-rs already depends on the Vulkan backend directly to enable X11 support, so this fix fits well.
The problem comes from the fact `gfx_select!` is in a different crate... but fortunately looks like we can live with that.
