### ISSUE TITLE
Examples crash on resize with DX11

### ISSUE THREAD

**Issue by branpk** [gfx-rs/wgpu-rs#689]
On the latest master, the `cube` example crashes when resizing the window while using DX11.

I'm on Windows 10 using NVIDIA GeForce GTX 1080 Ti, but this also happens when using "Microsoft Basic Render Driver" with DX11.

Relevant backtrace:
```
[3.059938 ERROR]()(no module): ResizeBuffers failed with 0x887a0001
thread 'main' panicked at 'failed to configure swap chain on creation: Window is in use', C:\Users\Brandon\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\4ebe1f5\wgpu-core\src\device\mod.rs:3922:26
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eb4fc71dc9024f15a0c9cc44bcc10c861e9d585e\/library\std\src\panicking.rs:493
   1: std::panicking::begin_panic_fmt
             at /rustc/eb4fc71dc9024f15a0c9cc44bcc10c861e9d585e\/library\std\src\panicking.rs:435
   2: wgpu_core::device::{{impl}}::device_create_swap_chain::{{closure}}<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx11::Backend>
             at C:\Users\Brandon\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\4ebe1f5\wgpu-core\src\device\mod.rs:3922
   3: core::result::Result<tuple<>, gfx_hal::window::SwapchainError>::map_err<tuple<>,gfx_hal::window::SwapchainError,wgpu_core::device::DeviceError,closure-2>
             at C:\Users\Brandon\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:595
   4: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_swap_chain<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx11::Backend>
             at C:\Users\Brandon\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\4ebe1f5\wgpu-core\src\device\mod.rs:3917
   5: wgpu::backend::direct::{{impl}}::device_create_swap_chain
             at .\src\backend\direct.rs:717
   6: wgpu::Device::create_swap_chain
             at .\src\lib.rs:1545
   7: cube::framework::start::{{closure}}<cube::Example>
             at .\examples\framework.rs:283
...
```

**Comment by kvark** [comment]
I think @cwfitzgerald was just fixing this

**Comment by cwfitzgerald** [comment]
Yeah this is fixed once https://github.com/gfx-rs/wgpu/pull/1101 merges in.

**Comment by cwfitzgerald** [comment]
Closing as the PR is on its way to be merged and I don't want to forget.
