### ISSUE TITLE
Segfault at graphics pipeline creation on Linux/Intel/Vulkan

### ISSUE THREAD

**Issue by ashpil** [gfx-rs/wgpu-rs#838]
Sorry for the rather useless title, but I don't really have any more info than that. I'm getting a segfault on running my program. See attached trace. I'm on the git version from commit `e835f2972dafe73011b24c1fecd48134f13ed949`.  Here is the call stack:

```gdb
#0  0x00007ffff75dc411 in ?? () from /usr/lib64/libvulkan_intel.so
#1  0x00007ffff72e1f77 in ?? () from /usr/lib64/libvulkan_intel.so
#2  0x00007ffff72e2b9a in ?? () from /usr/lib64/libvulkan_intel.so
#3  0x00007ffff72e47db in ?? () from /usr/lib64/libvulkan_intel.so
#4  0x00007ffff736177b in ?? () from /usr/lib64/libvulkan_intel.so
#5  0x00005555562b06ea in ash::vk::features::DeviceFnV1_0::create_graphics_pipelines (
    self=0x5555572fc428, device=..., pipeline_cache=..., create_info_count=1,
    p_create_infos=0x7fffffff3f00, p_allocator=0x0, p_pipelines=0x7fffffff49d8)
    at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.32.1/src/vk/features.rs:4977
#6  0x000055555627cac4 in gfx_backend_vulkan::device::{{impl}}::create_graphics_pipeline (
    self=0x5555572a2e18, desc=0x7fffffff6c70, cache=...)
    at /home/andrei/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/d002952/src/backend/vulkan/src/device.rs:792
#7  0x0000555555c583c5 in wgpu_core::device::Device<gfx_backend_vulkan::Backend>::create_render_pipeline<gfx_backend_vulkan::Backend,wgpu_core::hub::IdentityManagerFactory> (self=0x5555572a2e18, self_id=...,
    desc=0x7fffffff8cc0, implicit_context=..., hub=0x555556fba8a0, token=0x7fffffff8000)
    at /home/andrei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/41f106d/wgpu-core/src/device/mod.rs:2398
#8  0x0000555555d5df6a in wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_render_pipeline<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend> (
    self=0x555556fba770, device_id=..., desc=0x7fffffff8cc0, id_in=..., implicit_pipeline_ids=...)
    at /home/andrei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/41f106d/wgpu-core/src/device/mod.rs:4016
#9  0x0000555555c7531b in wgpu::backend::direct::{{impl}}::device_create_render_pipeline (
    self=0x555556fba770, device=0x7fffffff9578, desc=0x7fffffffa658)
    at /home/andrei/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/e835f29/src/backend/direct.rs:1007
#10 0x0000555555e03ee7 in wgpu::Device::create_render_pipeline (self=0x7fffffff9570,
    desc=0x7fffffffa658)
    at /home/andrei/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/e835f29/src/lib.rs:1578
#11 0x0000555555780377 in rasterization::context::{{impl}}::new::{{closure}} ()
    at /home/andrei/Documents/Classes/2021S/CS5625/Rasterization/src/context.rs:252
#12 0x0000555555768e57 in core::future::from_generator::{{impl}}::poll<generator-0> (self=...,
    cx=0x7fffffffbc30)
    at /rustc/52e3dffa50cfffdcfa145c0cc0ba48b49abc0c07/library/core/src/future/mod.rs:80
#13 0x0000555555781580 in futures_executor::local_pool::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>> (cx=0x7fffffffbc30)
    at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317
#14 0x0000555555781399 in futures_executor::local_pool::run_executor::{{closure}}<core::result::Result<rasterization::context::Context, anyhow::Error>,closure-0> (thread_notify=0x7ffff7c6f778)
    at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:87
#15 0x0000555555771452 in std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::try_with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,core::result::Result<rasterization::context::Context, anyhow::Error>> (self=0x555556e8ffa8, f=...)
    at /rustc/52e3dffa50cfffdcfa145c0cc0ba48b49abc0c07/library/std/src/thread/local.rs:272
#16 0x000055555577115a in std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,core::result::Result<rasterization::context::Context, anyhow::Error>> (self=0x555556e8ffa8, f=...)
    at /rustc/52e3dffa50cfffdcfa145c0cc0ba48b49abc0c07/library/std/src/thread/local.rs:248
#17 0x00005555557812ad in futures_executor::local_pool::run_executor<core::result::Result<rasterization::context::Context, anyhow::Error>,closure-0> (f=...)
    at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:83
#18 0x00005555557814e4 in futures_executor::local_pool::block_on<core::future::from_generator::GenFuture<generator-0>> (f=...)
    at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317
#19 0x00005555557860ee in rasterization::main () at src/main.rs:21
```
[trace.zip](https://github.com/gfx-rs/wgpu-rs/files/6253982/trace.zip)

**Comment by kvark** [comment]
Turned out, this is about Naga SPV-out issues https://github.com/gfx-rs/naga/issues/659, https://github.com/gfx-rs/naga/issues/660, and https://github.com/gfx-rs/naga/issues/654. Fixes are coming, will reach wgpu with the next train.
