### ISSUE TITLE
msaa-line demo crashes on Mac OS X with assertion failure.

### ISSUE THREAD

**Issue by mlindner** [gfx-rs/wgpu-rs#91]
When I attempted to change the sample count, the main thread paniced with an assertion failure.

Mac OS X 10.13.6
GPU: Intel HD Graphics 4000 1536 MB

Trace below:
```
mlindner$ RUST_BACKTRACE=1 cargo run --example msaa-line
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/examples/msaa-line`
Press left/right arrow keys to change sample_count.
sample_count: 4
sample_count: 8
thread 'main' panicked at 'Attachment sample_count must be supported by physical device limits', /Users/mlindner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c3609d7/wgpu-native/src/command/mod.rs:261:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:411
   8: wgpu_native::command::command_encoder_begin_render_pass
             at /Users/mlindner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c3609d7/wgpu-native/src/command/mod.rs:261
   9: wgpu_command_encoder_begin_render_pass
             at /Users/mlindner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c3609d7/wgpu-native/src/command/mod.rs:719
  10: wgpu::CommandEncoder::begin_render_pass
             at src/lib.rs:1058
  11: <msaa_line::Example as msaa_line::framework::Example>::render
             at examples/msaa-line/main.rs:214
  12: msaa_line::framework::run::{{closure}}
             at examples/msaa-line/../framework.rs:155
  13: <winit::platform_impl::platform::app_state::EventLoopHandler<F,T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/mlindner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/platform_impl/macos/app_state.rs:61
  14: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/mlindner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/platform_impl/macos/app_state.rs:169
  15: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/mlindner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/platform_impl/macos/app_state.rs:293
  16: winit::platform_impl::platform::observer::control_flow_end_handler
             at /Users/mlindner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/platform_impl/macos/observer.rs:136
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <() as objc::message::MessageArguments>::invoke
             at /Users/mlindner/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.6/src/message/mod.rs:128
  28: objc::message::platform::send_unverified
             at /Users/mlindner/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.6/src/message/apple/mod.rs:27
  29: objc::message::send_message
             at /Users/mlindner/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.6/src/message/mod.rs:178
  30: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at ./<::objc::macros::msg_send macros>:15
  31: winit::event_loop::EventLoop<T>::run
             at /Users/mlindner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/event_loop.rs:140
  32: msaa_line::framework::run
             at examples/msaa-line/../framework.rs:115
  33: msaa_line::main
             at examples/msaa-line/main.rs:228
  34: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  35: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  36: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  37: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  38: std::panicking::try
             at src/libstd/panicking.rs:275
  39: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  40: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  41: std::rt::lang_start
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  42: msaa_line::main
```

**Comment by kvark** [comment]
The WebGPU working group hasn't yet figured out how to expose the MSAA capabilities.

**Comment by edap** [comment]
Same here, with a different error message, I can confirm this bug on mac OS "El Capitan".

```
cargo run --example msaa-line
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/examples/msaa-line`
Press left/right arrow keys to change sample_count.
sample_count: 4
/Library/Caches/com.apple.xbs/Sources/Metal/Metal-56.6.1/Framework/MTLRenderPass.m:117: failed assertion `storeAction is not a valid MTLStoreAction.'
[1]    68259 abort      cargo run --example msaa-line
```

**Comment by kvark** [comment]
@edap this looks to be a different issue

**Comment by cwfitzgerald** [comment]
I have a similar issue on windows with the msaa-line example on a card that definitely supports 4x MSAA (1080ti). It crashes on launch saying that the device doesn't support that msaa level.
