### ISSUE TITLE
texture sampling in vertex shader crashes on vulkan

### ISSUE THREAD

**Issue by Ruddle** [gfx-rs/wgpu-rs#94]
It works with dx12 but crashes with vulkan backend (both on windows and linux, same trace).

RTX 2070

trace :
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ERROR_DEVICE_LOST)`', C:\Users\ctrl\.cargo\git\checkouts\gfx-e86e7f3ebdbc4218\3d5db15\src\backend\vulkan\src\lib.rs:1156:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.34\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:384
   7: std::panicking::begin_panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:339
   8: gfx_backend_vulkan::{{impl}}::submit<gfx_backend_vulkan::command::CommandBuffer,core::iter::adapters::flatten::FlatMap<core::slice::Iter<wgpu_native::id::Id<wgpu_native::command::CommandBuffer<gfx_backend_empty::Backend>>>, alloc::vec::Vec<gfx_backend_vul
             at <::std::macros::panic macros>:8
   9: wgpu_native::device::queue_submit<gfx_backend_vulkan::Backend>
             at C:\Users\ctrl\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\c3609d7\wgpu-native\src\device.rs:1527
  10: wgpu_native::device::wgpu_queue_submit
             at C:\Users\ctrl\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\c3609d7\wgpu-native\src\device.rs:1568
  11: wgpu::Queue::submit
             at .\src\lib.rs:1332
  12: cube::framework::run::{{closure}}<cube::Example>
             at .\examples\framework.rs:156
  13: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
             at C:\Users\ctrl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha3\src\platform_impl\windows\event_loop.rs:178
  14: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\liballoc\boxed.rs:794
  15: winit::platform_impl::platform::event_loop::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\ctrl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha3\src\platform_impl\windows\event_loop.rs:547
  16: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panic.rs:315
  17: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panicking.rs:296
  18: panic_unwind::__rust_maybe_catch_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libpanic_unwind\lib.rs:80
  19: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panicking.rs:275
  20: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panic.rs:394
  21: winit::platform_impl::platform::event_loop::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\ctrl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha3\src\platform_impl\windows\event_loop.rs:545
  22: winit::platform_impl::platform::event_loop::EventLoopRunner<()>::events_cleared<()>
             at C:\Users\ctrl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha3\src\platform_impl\windows\event_loop.rs:484
  23: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\Users\ctrl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha3\src\platform_impl\windows\event_loop.rs:225
  24: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\ctrl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha3\src\platform_impl\windows\event_loop.rs:162
  25: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\ctrl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha3\src\event_loop.rs:140
  26: cube::framework::run<cube::Example>
             at .\examples\framework.rs:115
  27: cube::main
             at .\examples\cube\main.rs:357
  28: std::rt::lang_start::{{closure}}<()>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\rt.rs:64
  29: std::rt::lang_start_internal::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:49
  30: std::panicking::try::do_call<closure-0,i32>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:296
  31: panic_unwind::__rust_maybe_catch_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libpanic_unwind\lib.rs:80
  32: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:275
  33: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panic.rs:394
  34: std::rt::lang_start_internal
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:48
  35: std::rt::lang_start<()>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\rt.rs:64
  36: main
  37: invoke_main
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  38: __scrt_common_main_seh
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  39: BaseThreadInitThunk
  40: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\cube.exe` (exit code: 101)
```

step to reproduce : take the cube example and change the shaders to the following :

shader.vert
```glsl
#version 450
layout(set = 0, binding = 1) uniform texture2D t_Color;
layout(set = 0, binding = 2) uniform sampler s_Color;
void main() {
    gl_Position = texture(sampler2D(t_Color, s_Color), vec2(0.0,0.0));
}
```

shader.frag
```glsl
#version 450
layout(location = 0) out vec4 o_Target;
void main() {
    o_Target =  vec4(0.0);
}
```

Both glsl_to_spirv and shaderc compilation of the shaders have the same behavior.

**Comment by kvark** [comment]
You can't just move bindings around in the shader without adjusting the binding model, which is represented by the `BindGroupLayout` and `PipelineLayout` objects. In this case, the texture and sampler are specified to only be visible to the `FRAGMENT` stage:
https://github.com/gfx-rs/wgpu-rs/blob/cb25914b95b58fee0dc139b400867e7a731d98f4/examples/cube/main.rs#L138

If you run with Vulkan validation, you'd see the relevant errors.

---
The goal of this library to be fully safe and don't permit such errors to happen. We will be introspecting the shaders and validating their interfaces against the binding model in the future. Closing as a custom case of https://github.com/gfx-rs/wgpu/issues/269 . Feel free to re-open if I missed anything!
